import LeanTrominoes.Assignment
import LeanTrominoes.Computability
import LeanTrominoes.ComputableSearch
import LeanTrominoes.EncodingBounds
import LeanTrominoes.FiniteSearch
import LeanTrominoes.FiniteState
import LeanTrominoes.FiniteStateCycleSearch
import LeanTrominoes.FiniteStateReachability
import LeanTrominoes.FiniteStateSearch
import LeanTrominoes.FiniteTMCompiler
import LeanTrominoes.FootprintTiling
import LeanTrominoes.Gadget
import LeanTrominoes.GadgetAssembly
import LeanTrominoes.GadgetBehavior
import LeanTrominoes.GadgetColoring
import LeanTrominoes.GadgetLibrary
import LeanTrominoes.GadgetLPhaseLift
import LeanTrominoes.GadgetLPhaseTable
import LeanTrominoes.GadgetOrientation
import LeanTrominoes.GadgetOrientationBehavior
import LeanTrominoes.GadgetIOrientationBehavior
import LeanTrominoes.GadgetIPortRefinement
import LeanTrominoes.GadgetIPhaseTable
import LeanTrominoes.GadgetIPhaseLift
import LeanTrominoes.GadgetPortRefinement
import LeanTrominoes.GadgetPorts
import LeanTrominoes.GadgetReduction
import LeanTrominoes.GadgetReductionComputability
import LeanTrominoes.GadgetSubstitution
import LeanTrominoes.GadgetWire
import LeanTrominoes.OrthogonalDrawing
import LeanTrominoes.PartrecFiniteEvaluator
import LeanTrominoes.PartrecPolySpace
import LeanTrominoes.StripFrontier
import LeanTrominoes.StripFrontierCorrectness
import LeanTrominoes.StripFrontierEncoding
import LeanTrominoes.StripFrontierIndex
import LeanTrominoes.StripFrontierReconstruction
import LeanTrominoes.StripFrontierSpace
import LeanTrominoes.Theorem52
import LeanTrominoes.TilingCompactness

/-!
# LeanTrominoes

Formalization of the results in *Undecidability of Tiling with a Tromino*.
-/
