import LeanTrominoes.Assignment
import LeanTrominoes.Computability
import LeanTrominoes.ComputableSearch
import LeanTrominoes.EncodingBounds
import LeanTrominoes.FiniteSearch
import LeanTrominoes.FiniteState
import LeanTrominoes.FiniteStateCycleSearch
import LeanTrominoes.FiniteStateReachability
import LeanTrominoes.FiniteStateSearch
import LeanTrominoes.FootprintTiling
import LeanTrominoes.Gadget
import LeanTrominoes.GadgetAssembly
import LeanTrominoes.GadgetBehavior
import LeanTrominoes.GadgetColoring
import LeanTrominoes.GadgetLibrary
import LeanTrominoes.GadgetLPhaseTable
import LeanTrominoes.GadgetOrientation
import LeanTrominoes.GadgetOrientationBehavior
import LeanTrominoes.GadgetPortRefinement
import LeanTrominoes.GadgetPorts
import LeanTrominoes.GadgetSubstitution
import LeanTrominoes.GadgetWire
import LeanTrominoes.OrthogonalDrawing
import LeanTrominoes.StripFrontier
import LeanTrominoes.StripFrontierCorrectness
import LeanTrominoes.StripFrontierReconstruction
import LeanTrominoes.StripFrontierSpace
import LeanTrominoes.Theorem52
import LeanTrominoes.TilingCompactness

/-!
# LeanTrominoes

Formalization of the results in *Undecidability of Tiling with a Tromino*.
-/
