/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix12 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail12 = true := by decide +kernel

theorem certificatePrefix13 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail13 = true := by decide +kernel

theorem certificatePrefix14 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail14 = true := by decide +kernel

theorem certificatePrefix15 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail15 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
