/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix32 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail32 = true := by decide +kernel

theorem certificatePrefix33 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail33 = true := by decide +kernel

theorem certificatePrefix34 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail34 = true := by decide +kernel

theorem certificatePrefix35 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail35 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
