/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix36 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail36 = true := by decide +kernel

theorem certificatePrefix37 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail37 = true := by decide +kernel

theorem certificatePrefix38 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail38 = true := by decide +kernel

theorem certificatePrefix39 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail39 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
