/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix16 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail16 = true := by decide +kernel

theorem certificatePrefix17 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail17 = true := by decide +kernel

theorem certificatePrefix18 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail18 = true := by decide +kernel

theorem certificatePrefix19 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail19 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
