/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix20 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail20 = true := by decide +kernel

theorem certificatePrefix21 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail21 = true := by decide +kernel

theorem certificatePrefix22 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail22 = true := by decide +kernel

theorem certificatePrefix23 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail23 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
