/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix28 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail28 = true := by decide +kernel

theorem certificatePrefix29 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail29 = true := by decide +kernel

theorem certificatePrefix30 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail30 = true := by decide +kernel

theorem certificatePrefix31 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail31 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
