/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedDupCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedDup
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix40 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail40 = true := by decide +kernel

theorem certificatePrefix41 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail41 = true := by decide +kernel

theorem certificatePrefix42 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail42 = true := by decide +kernel

theorem certificatePrefix43 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail43 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedDup
