/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanTrominoes.FiniteTrominoCompletion
import Mathlib.Data.Int.Interval

/-! # Fully prefilled collars for false strip-boundary connectors

Generated by `scripts/completion_strip_caps.py`. The top collar has two
full rows and a half-width third row. The bottom collar is its half-turn.
The solver is untrusted; both finite tilings are checked by the kernel.
-/
namespace LeanTrominoes.CompletionPattern.StripCaps

def width : Tromino → Int | .L => 12 | .I => 18

def topRegion (t : Tromino) : Finset Cell :=
  ((Finset.Ico 0 (width t)).product (Finset.Ico 0 3)).filter
    (fun c => c.2 < 2 ∨ c.1 < width t / 2)

def bottomRegion (t : Tromino) : Finset Cell :=
  ((Finset.Ico 0 (width t)).product (Finset.Ico 0 3)).filter
    (fun c => 0 < c.2 ∨ width t / 2 ≤ c.1)


def topMotif : Tromino → List (Placement Unit)
  | .L => [⟨(),.identity,(0,0)⟩,⟨(),.rotate180,(1,2)⟩,⟨(),.identity,(2,0)⟩,⟨(),.rotate180,(3,2)⟩,⟨(),.identity,(4,0)⟩,⟨(),.rotate180,(5,2)⟩,⟨(),.identity,(6,0)⟩,⟨(),.rotate180,(8,1)⟩,⟨(),.identity,(9,0)⟩,⟨(),.rotate180,(11,1)⟩]
  | .I => [⟨(),.identity,(15,0)⟩,⟨(),.identity,(12,0)⟩,⟨(),.identity,(9,0)⟩,⟨(),.identity,(15,1)⟩,⟨(),.identity,(12,1)⟩,⟨(),.identity,(9,1)⟩,⟨(),.rotate90,(0,0)⟩,⟨(),.rotate90,(1,0)⟩,⟨(),.rotate90,(2,0)⟩,⟨(),.rotate90,(3,0)⟩,⟨(),.rotate90,(4,0)⟩,⟨(),.rotate90,(5,0)⟩,⟨(),.rotate90,(6,0)⟩,⟨(),.rotate90,(7,0)⟩,⟨(),.rotate90,(8,0)⟩]

theorem top_tiling (t : Tromino) :
    IsFiniteTiling (fun _ => t.cells) (topRegion t) (topMotif t).toFinset := by
  cases t <;> decide +kernel


def bottomMotif : Tromino → List (Placement Unit)
  | .L => [⟨(),.identity,(0,1)⟩,⟨(),.rotate180,(2,2)⟩,⟨(),.identity,(3,1)⟩,⟨(),.rotate180,(5,2)⟩,⟨(),.identity,(6,0)⟩,⟨(),.rotate180,(7,2)⟩,⟨(),.identity,(8,0)⟩,⟨(),.rotate180,(9,2)⟩,⟨(),.identity,(10,0)⟩,⟨(),.rotate180,(11,2)⟩]
  | .I => [⟨(),.identity,(0,1)⟩,⟨(),.identity,(0,2)⟩,⟨(),.identity,(3,1)⟩,⟨(),.identity,(3,2)⟩,⟨(),.identity,(6,1)⟩,⟨(),.identity,(6,2)⟩,⟨(),.rotate90,(9,0)⟩,⟨(),.rotate90,(10,0)⟩,⟨(),.rotate90,(11,0)⟩,⟨(),.rotate90,(12,0)⟩,⟨(),.rotate90,(13,0)⟩,⟨(),.rotate90,(14,0)⟩,⟨(),.rotate90,(15,0)⟩,⟨(),.rotate90,(16,0)⟩,⟨(),.rotate90,(17,0)⟩]

theorem bottom_tiling (t : Tromino) :
    IsFiniteTiling (fun _ => t.cells) (bottomRegion t) (bottomMotif t).toFinset := by
  cases t <;> decide +kernel


end LeanTrominoes.CompletionPattern.StripCaps
