/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanTrominoes.CompletionPeriodicCertificate
import Mathlib.Data.List.OfFn

/-! # Extracting finite certificates from geometric periodic completions -/
namespace LeanTrominoes.CompletionPeriodic
open PeriodicTrominoPrefill TrominoAssignment
set_option maxHeartbeats 2000000

/-- Invariance under the square lattice generated by `(n,0)` and `(0,n)`. -/
def HasSquarePeriod (completed : Set (Finset Cell)) (n : Nat) : Prop :=
  ∀ f k, f ∈ completed ↔ f.image (Cell.add (Cell.scale (n:Int) k)) ∈ completed

def PeriodicallyCompletable (t : Tromino) (input : PeriodicTrominoPrefill) : Prop :=
  ∃ completed, t.IsFootprintTiling Set.univ completed ∧ input.prescribed t ⊆ completed ∧
    ∃ n, 0 < n ∧ HasSquarePeriod completed n

/-- Accepted tables themselves give square-periodic completions. -/
theorem periodic_of_certificate (t : Tromino) (input : PeriodicTrominoPrefill)
    (w : Certificate) (h : Check t input w) : PeriodicallyCompletable t input := by
  refine ⟨Set.range (tile t w),check_tiling t input w h,check_retained t input w h,w.1,h.1,?_⟩
  intro f k
  let v := Cell.scale (w.1:Int) k
  have translate (c : Cell) : tile t w (Cell.add c v) = (tile t w c).image (Cell.add v) := by
    apply tile_translate
    ext <;> simp [residue,Cell.add,v,Cell.scale,Int.add_emod,Int.mul_emod]
  constructor
  · rintro ⟨c,rfl⟩; exact ⟨Cell.add c v,(translate c)⟩
  · rintro ⟨c,hc⟩
    refine ⟨Cell.sub c v,?_⟩
    apply (Finset.image_inj (Cell.add_left_injective v)).mp
    rw [← translate,show Cell.add (Cell.sub c v) v = c by ext <;> simp [Cell.add,Cell.sub]]
    exact hc

private theorem table_exists (n : Nat) (hn : 0 < n) (p : Cell → Placement Unit) :
    ∃ ps : List (Placement Unit), ∀ c, entry (n,ps) c = p (residue n c) := by
  let ps := List.ofFn fun i : Fin (n*n) => p ((i.val/n:Nat),(i.val%n:Nat))
  refine ⟨ps,?_⟩
  intro c
  have pos : (0:Int) < n := by exact_mod_cast hn
  have x0 := Int.emod_nonneg c.1 (ne_of_gt pos)
  have y0 := Int.emod_nonneg c.2 (ne_of_gt pos)
  have xb := Int.emod_lt_of_pos c.1 pos
  have yb := Int.emod_lt_of_pos c.2 pos
  have xn : (c.1 % (n:Int)).toNat < n := by omega
  have yn : (c.2 % (n:Int)).toNat < n := by omega
  have kb : key n c < n*n := by
    dsimp [key,residue]; nlinarith
  have dx : key n c / n = (c.1 % (n:Int)).toNat := by
    dsimp [key,residue]
    rw [Nat.add_comm, Nat.add_mul_div_right _ _ hn, Nat.div_eq_of_lt yn, Nat.zero_add]
  have dy : key n c % n = (c.2 % (n:Int)).toNat := by
    simp [key,residue,Nat.add_mod, Nat.mod_eq_of_lt yn]
  simp only [entry,ps,List.getD,List.getElem?_ofFn,dif_pos kb,Option.getD_some,dx,dy,residue,Int.toNat_of_nonneg x0,Int.toNat_of_nonneg y0]

/-- Every geometric periodic completion has a finite accepted certificate. -/
theorem certificate_of_periodic (t : Tromino) (input : PeriodicTrominoPrefill)
    (h : PeriodicallyCompletable t input) : ∃ w, Check t input w := by
  classical
  obtain ⟨completed,tiling,retained,n,hn,periodic⟩ := h
  choose cover coverData coverUnique using fun c => tiling.uniqueCover c (Set.mem_univ c)
  have legal (c : Cell) : t.IsFootprint ((cover c).image (Cell.add (Cell.sub (0,0) c))) :=
    (tiling.tilesInside (cover c) (coverData c).1).1.translate _
  choose p hp using legal
  obtain ⟨ps,hps⟩ := table_exists n hn p
  let w : Certificate := (n,ps)
  have imageEq (c : Cell) : tile t w c = (cover (residue n c)).image (Cell.add (Cell.sub c (residue n c))) := by
    rw [tile_eq_image,hps,hp,Finset.image_image]
    congr 1; funext d; ext <;> simp [Cell.add,Cell.sub] <;> ring
  have selected (c : Cell) : tile t w c ∈ completed := by
    rw [imageEq]
    have offset : Cell.sub c (residue n c) = Cell.scale (n:Int) (c.1/(n:Int),c.2/(n:Int)) := by
      ext <;> simp [Cell.sub,residue,Cell.scale,Int.emod_def]
    rw [offset]
    exact (periodic _ _).mp (coverData _).1
  have contains (c : Cell) : c ∈ tile t w c := by
    rw [imageEq]
    exact Finset.mem_image.mpr ⟨residue n c,(coverData _).2,by ext <;> simp [Cell.add,Cell.sub]⟩
  have agrees (c d : Cell) (hd : d ∈ tile t w c) : tile t w d = tile t w c :=
    (coverUnique d _ ⟨selected d,contains d⟩).trans (coverUnique d _ ⟨selected c,hd⟩).symm
  refine ⟨w,hn,?_,?_⟩
  · intro c _
    exact ⟨List.mem_toFinset.mp (contains c), fun d hd => (sameCells_iff _ _).mpr (agrees c d (List.mem_toFinset.mpr hd))⟩
  · intro index _ q hq
    apply (sameCells_iff _ _).mpr
    rw [repeatedCells_toFinset]
    let f := (q.cells (fun _ => t.cells)).image (Cell.add (repeatOffset input index))
    have hf : f ∈ completed := retained ⟨q,hq,index.1,index.2,rfl⟩
    have hc : Cell.add (repeatOffset input index) q.offset ∈ f :=
      Finset.mem_image.mpr ⟨q.offset,t.offset_mem_placement_cells q,rfl⟩
    exact (coverUnique _ f ⟨hf,hc⟩).trans (coverUnique _ _ ⟨selected _,contains _⟩).symm
/-- Invariance under a full-rank lattice of integer translation vectors. -/
def HasIndependentPeriods (completed : Set (Finset Cell)) : Prop :=
  ∃ a b : Cell, a.1*b.2-a.2*b.1 ≠ 0 ∧
    ∀ f (i j : Int), f ∈ completed ↔
      f.image (Cell.add (Cell.add (Cell.scale i a) (Cell.scale j b))) ∈ completed

/-- Every full-rank integer period lattice contains a square sublattice. -/
theorem squarePeriod_of_independent {completed : Set (Finset Cell)}
    (h : HasIndependentPeriods completed) : ∃ n, 0 < n ∧ HasSquarePeriod completed n := by
  obtain ⟨a,b,nonzero,h⟩ := h
  let d := a.1*b.2-a.2*b.1
  have dn : d ≠ 0 := nonzero
  refine ⟨d.natAbs,Int.natAbs_pos.mpr dn,?_⟩
  intro f k
  have calcPeriod (sign : Int) (eq : (d.natAbs:Int) = sign*d) :
      Cell.scale (d.natAbs:Int) k =
        Cell.add (Cell.scale (sign*(b.2*k.1-b.1*k.2)) a)
          (Cell.scale (sign*(a.1*k.2-a.2*k.1)) b) := by
    rw [eq]; ext <;> dsimp [Cell.scale,Cell.add,d] <;> ring
  by_cases positive : 0 ≤ d
  · rw [calcPeriod 1 (by simp [abs_of_nonneg positive])]
    exact h f _ _
  · rw [calcPeriod (-1) (by simp [abs_of_neg (lt_of_not_ge positive)])]
    exact h f _ _

end LeanTrominoes.CompletionPeriodic
