/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionPatternIndexed

noncomputable section

namespace LeanTrominoes.CompletionPattern.LPlugTopBoundary

set_option compiler.extract_closed false
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

noncomputable def prefillList : List (Placement Unit) := [⟨(),.identity,(0,1)⟩,⟨(),.identity,(0,3)⟩,⟨(),.rotate270,(0,6)⟩,⟨(),.rotate180,(2,2)⟩,⟨(),.identity,(3,1)⟩,⟨(),.rotate180,(4,6)⟩,⟨(),.rotate180,(5,2)⟩,⟨(),.identity,(5,5)⟩,⟨(),.identity,(6,0)⟩,⟨(),.rotate90,(7,2)⟩,⟨(),.rotate90,(8,1)⟩,⟨(),.rotate90,(9,0)⟩,⟨(),.rotate180,(9,3)⟩,⟨(),.rotate90,(9,4)⟩,⟨(),.identity,(10,0)⟩,⟨(),.rotate180,(11,2)⟩,⟨(),.identity,(10,3)⟩,⟨(),.rotate180,(11,5)⟩]
noncomputable def fixedCells : List Cell := [(0,1),(0,2),(0,3),(0,4),(0,5),(0,6),(1,1),(1,2),(1,3),(1,6),(2,1),(2,2),(3,1),(3,2),(3,6),(4,1),(4,2),(4,5),(4,6),(5,1),(5,2),(5,5),(5,6),(6,0),(6,1),(6,2),(6,5),(7,0),(7,1),(7,2),(7,3),(8,0),(8,1),(8,2),(8,3),(8,4),(9,0),(9,1),(9,2),(9,3),(9,4),(9,5),(10,0),(10,1),(10,2),(10,3),(10,4),(10,5),(11,0),(11,1),(11,2),(11,3),(11,4),(11,5)]
noncomputable def prefillSet : Finset (Placement Unit) := ⟨(↑prefillList : Multiset (Placement Unit)),by decide +kernel⟩
noncomputable def pattern : Pattern :=
  ⟨.L,⟨(↑([(0,1),(0,2),(0,3),(0,4),(0,5),(0,6),(1,1),(1,2),(1,3),(1,4),(1,5),(1,6),(2,0),(2,1),(2,2),(2,3),(2,4),(2,5),(2,6),(3,1),(3,2),(3,3),(3,4),(3,5),(3,6),(4,1),(4,2),(4,3),(4,4),(4,5),(4,6),(5,1),(5,2),(5,3),(5,4),(5,5),(5,6),(6,0),(6,1),(6,2),(6,3),(6,4),(6,5),(7,0),(7,1),(7,2),(7,3),(7,4),(7,5),(8,0),(8,1),(8,2),(8,3),(8,4),(8,5),(8,6),(9,0),(9,1),(9,2),(9,3),(9,4),(9,5),(10,0),(10,1),(10,2),(10,3),(10,4),(10,5),(11,0),(11,1),(11,2),(11,3),(11,4),(11,5)] : List Cell) : Multiset Cell),by decide +kernel⟩,prefillSet⟩

noncomputable def outside (i : Fin 16) : Finset Cell := match i.val with
  | 0 => ⟨(↑([] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 1 => ⟨(↑([(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 2 => ⟨(↑([(2,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 3 => ⟨(↑([(2,6),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 4 => ⟨(↑([(8,0)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 5 => ⟨(↑([(8,0),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 6 => ⟨(↑([(2,6),(8,0)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 7 => ⟨(↑([(2,6),(8,0),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 8 => ⟨(↑([(2,0)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 9 => ⟨(↑([(2,0),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 10 => ⟨(↑([(2,0),(2,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 11 => ⟨(↑([(2,0),(2,6),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 12 => ⟨(↑([(2,0),(8,0)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 13 => ⟨(↑([(2,0),(8,0),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | 14 => ⟨(↑([(2,0),(2,6),(8,0)] : List Cell) : Multiset Cell),by decide +kernel⟩
  | _ => ⟨(↑([(2,0),(2,6),(8,0),(8,6)] : List Cell) : Multiset Cell),by decide +kernel⟩

noncomputable def accepted (i : Fin 16) : Bool := match i.val with
  | 0 => false
  | 1 => false
  | 2 => false
  | 3 => false
  | 4 => false
  | 5 => false
  | 6 => false
  | 7 => false
  | 8 => false
  | 9 => true
  | 10 => true
  | 11 => false
  | 12 => false
  | 13 => false
  | 14 => false
  | _ => false

noncomputable def solutionList (i : Fin 16) : List (Placement Unit) := match i.val with
  | 0 => []
  | 1 => []
  | 2 => []
  | 3 => []
  | 4 => []
  | 5 => []
  | 6 => []
  | 7 => []
  | 8 => []
  | 9 => [⟨(),.rotate270,(7,5)⟩,⟨(),.identity,(2,5)⟩,⟨(),.identity,(1,4)⟩,⟨(),.rotate90,(3,3)⟩,⟨(),.identity,(4,3)⟩,⟨(),.rotate180,(6,4)⟩]
  | 10 => [⟨(),.rotate90,(8,5)⟩,⟨(),.rotate270,(6,4)⟩,⟨(),.rotate270,(1,5)⟩,⟨(),.identity,(3,4)⟩,⟨(),.identity,(2,3)⟩,⟨(),.rotate90,(5,3)⟩]
  | 11 => []
  | 12 => []
  | 13 => []
  | 14 => []
  | _ => []

noncomputable def solution (i : Fin 16) := (solutionList i).toFinset

noncomputable def residualList (i : Fin 16) : List Cell := match i.val with
  | 0 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 1 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 2 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 3 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 4 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 5 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 6 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 7 => [(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 8 => [(1,4),(1,5),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 9 => [(1,4),(1,5),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 10 => [(1,4),(1,5),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 11 => [(1,4),(1,5),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 12 => [(1,4),(1,5),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | 13 => [(1,4),(1,5),(2,3),(2,4),(2,5),(2,6),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]
  | 14 => [(1,4),(1,5),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5),(8,6)]
  | _ => [(1,4),(1,5),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)]

noncomputable def exclusion0 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(1,4),(1,5),(2,0),(2,3),(2,4),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4),(7,4),(7,5),(8,5)] : List Cell) : Multiset Cell),by decide +kernel⟩,(2,0),[]⟩
noncomputable def exclusion1 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(1,4),(2,3),(2,4),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(1,4),[1]⟩
noncomputable def exclusion2 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(2,3),(2,5),(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(2,3),[2]⟩
noncomputable def exclusion3 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(3,3),(3,4),(3,5),(4,3),(4,4),(5,3),(5,4),(6,3),(6,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(3,5),[2]⟩
noncomputable def exclusion4 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(2,3),(3,3),(4,3),(4,4),(5,3),(5,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(2,3),[]⟩
noncomputable def exclusion5 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(2,5),(3,5),(4,3),(4,4),(5,3),(5,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(2,5),[]⟩
noncomputable def exclusion6 : TrominoFiniteIndexedExclusion.Node := ⟨⟨(↑([(3,3),(4,3),(5,3),(5,4),(6,3),(6,4)] : List Cell) : Multiset Cell),by decide +kernel⟩,(3,3),[]⟩

noncomputable def certificate : List TrominoFiniteIndexedExclusion.Node := [exclusion0,exclusion1,exclusion2,exclusion3,exclusion4,exclusion5,exclusion6]

end LeanTrominoes.CompletionPattern.LPlugTopBoundary
