/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionLPlugTopBoundaryData

namespace LeanTrominoes.CompletionPattern.LPlugTopBoundary

set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificate_checked :
    TrominoFiniteIndexedExclusion.check pattern.tromino certificate = true := by decide +kernel

theorem prefill_checked :
    IsFiniteTiling (fun _ => pattern.tromino.cells) pattern.fixedRegion pattern.prefill := by
  decide +kernel

theorem solutions_checked (i : Fin 16) : accepted i = true →
    IsFiniteTiling (fun _ => pattern.tromino.cells) (pattern.residual (outside i)) (solution i) ∧
      (∀ q ∈ pattern.prefill, q.cells (fun _ => pattern.tromino.cells) ⊆ pattern.target (outside i)) := by
  revert i
  decide +kernel

theorem rejections_checked (i : Fin 16) : accepted i = false →
    pattern.rejectsIndexed (outside i) certificate = true := by
  unfold Pattern.rejectsIndexed
  rw [certificate_checked]
  revert i
  decide +kernel

theorem completable_iff (i : Fin 16) :
    pattern.Completable (outside i) ↔ accepted i = true := by
  cases h : accepted i
  · exact iff_of_false (pattern.not_completable_of_rejectsIndexed _ certificate (rejections_checked i h)) (by decide)
  · exact iff_of_true (pattern.completable_of_residual_solution _ _ prefill_checked (solutions_checked i h).2 (solutions_checked i h).1) rfl

end LeanTrominoes.CompletionPattern.LPlugTopBoundary
