/- Generated by scripts/completion_orientation_circuits.py. -/
import LeanTrominoes.CompletionCircuitBlankData
import LeanTrominoes.CompletionCircuitHorizontalData
import LeanTrominoes.CompletionCircuitVerticalData
import LeanTrominoes.CompletionCircuitNorthwestData
import LeanTrominoes.CompletionCircuitSoutheastData
import LeanTrominoes.CompletionCircuitNortheastData
import LeanTrominoes.CompletionCircuitSouthwestData
import LeanTrominoes.CompletionCircuitCopyData
import LeanTrominoes.CompletionCircuitExactoneData

noncomputable section
namespace LeanTrominoes.CompletionPattern.LBricks

set_option Elab.async false
set_option maxHeartbeats 0
set_option maxRecDepth 65536

def circuitFor : CircuitKind → Circuit
  | .blank => CircuitData.Blank.circuit
  | .horizontal => CircuitData.Horizontal.circuit
  | .vertical => CircuitData.Vertical.circuit
  | .northwest => CircuitData.Northwest.circuit
  | .southeast => CircuitData.Southeast.circuit
  | .northeast => CircuitData.Northeast.circuit
  | .southwest => CircuitData.Southwest.circuit
  | .copy => CircuitData.Copy.circuit
  | .exactone => CircuitData.Exactone.circuit

/-- Exact terminal truth tables for the nine orientation-cell circuits. -/
theorem circuit_truth_table (kind : CircuitKind) : (circuitFor kind).TruthTableCorrect kind := by
  cases kind <;> decide +kernel

end LeanTrominoes.CompletionPattern.LBricks
