/- Generated by scripts/completion_orientation_circuits.py. -/
import LeanTrominoes.CompletionCircuit

noncomputable section
namespace LeanTrominoes.CompletionPattern.LBricks.CircuitData.Blank

def circuit : Circuit where
  nodes := [
]
  clauseCount := 0
  anchors := [0,0,0,0]
  terminals := [none,none,none,none]

end LeanTrominoes.CompletionPattern.LBricks.CircuitData.Blank
