/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFStripDirectSourceFinalClauseDescriptorSemantics
import LeanTrominoes.PeriodicCNFStripDirectSourceFinalCopiedInheritedRingAtomCodeCompiler
import LeanTrominoes.PeriodicCNFStripHorizontalRoutedRouteHeaderPresentationAtomScopeCompiler
import LeanTrominoes.PeriodicEightOccurrenceSplitTerminalPortGeometry

/-! # Ring-vertex slots of direct final cycle occurrences -/

noncomputable section

namespace LeanTrominoes.PeriodicCNFStripReduction

open Computability Turing PeriodicCNF
open OccurrenceSplitRing
open PeriodicCNF.ClauseProfilePolarityRouteOperation

variable {Input : Type}
variable {encoding : _root_.Computability.FinEncoding Input}
variable {language : Input → Prop}
variable (decider : Complexity.DeciderInPolySpace encoding language)

noncomputable local instance directFinalCycleRingVertexSlotStackFintype
    (stack : decider.tm.K) : Fintype (decider.tm.Γ stack) :=
  decider.stackAlphabetFinite stack

/-- The eight port ranks followed by the separator slot. -/
abbrev DirectFinalCycleRingVertexSlot := Fin fixedEightRingVertexCount

instance : Inhabited DirectFinalCycleRingVertexSlot :=
  ⟨⟨0, by unfold fixedEightRingVertexCount; omega⟩⟩

/-- Base-nine slot of a local implication-ring vertex.  Port numbering agrees
with the retained source terminal-slot compiler. -/
def directFinalCycleRingVertexSlot :
    RingVertex → DirectFinalCycleRingVertexSlot
  | .separator => ⟨8, by decide⟩
  | .port port =>
      ⟨port.angularRank,
        (port.angularRank_lt_eight).trans (by decide)⟩

/-- Ring vertex selected by an inherited presentation-relative literal slot
of the implication clause beginning at `vertex`.  The impossible third slot
and all parent-local controls carry a harmless zero. -/
def directFinalCycleRingVertexSlotOfControl (vertex : RingVertex) :
    HorizontalRoutedRouteHeader.AtomScopeControl →
      DirectFinalCycleRingVertexSlot
  | .inherited .first => directFinalCycleRingVertexSlot vertex
  | .inherited .second => directFinalCycleRingVertexSlot vertex.next
  | .inherited .third => default
  | .parentLocal _ => default

/-- Ring slots for all final Figure 9 occurrences generated by one local
implication clause and its corresponding cycle vertex. -/
def directSourceFinalCycleClauseRingVertexSlotBlock
    (tagged : RingVertex × FormulaShapeDirectionOrdering.Token) :
    List DirectFinalCycleRingVertexSlot :=
  match tagged.2 with
  | .variable => []
  | .clause profile =>
      (HorizontalRoutedRouteHeaderPresentationAtomScope.clauseBlock
        profile).map
          (directFinalCycleRingVertexSlotOfControl tagged.1)

/-- Complete fixed ring-slot table for one implication cycle. -/
def directSourceFinalLocalCycleRingVertexSlots :
    List DirectFinalCycleRingVertexSlot :=
  (List.zip OccurrenceSplitRing.presentedCycleVertices
      FormulaShapeFixedEightDirection.cycleClauseDescriptors).flatMap
    directSourceFinalCycleClauseRingVertexSlotBlock

/-- Each retained-variable marker emits the same complete ring-slot table. -/
def directSourceFinalCycleRingVertexSlotBlock :
    FormulaShapeDirectionOrdering.Token →
      List DirectFinalCycleRingVertexSlot
  | .variable => directSourceFinalLocalCycleRingVertexSlots
  | .clause _ => []

def directSourceFinalCycleRingVertexSlots
    (symbols : List encoding.Γ) :
    List DirectFinalCycleRingVertexSlot :=
  (directRetainedFigureNineFiniteSourceVariableMarkers
    decider symbols).flatMap directSourceFinalCycleRingVertexSlotBlock

/-- Unary numeric form of the complete cycle ring-slot column. -/
def directSourceFinalCycleRingVertexSlotValues
    (symbols : List encoding.Γ) : List Nat :=
  (directSourceFinalCycleRingVertexSlots decider symbols).map Fin.val

/-- Exhaustive verification of the fixed cycle table's exact occurrence
arity. -/
@[simp] theorem directSourceFinalLocalCycleRingVertexSlots_length :
    directSourceFinalLocalCycleRingVertexSlots.length =
      (HorizontalRoutedRouteHeaderOccurrenceBlock.output
        FormulaShapeFixedEightDirection.cycleClauseDescriptors).length := by
  native_decide

theorem directSourceFinalCycleRingVertexSlotBlock_length
    (token : FormulaShapeDirectionOrdering.Token) :
    (directSourceFinalCycleRingVertexSlotBlock token).length =
      (HorizontalRoutedRouteHeaderOccurrenceBlock.output
        (directSourceFinalCycleClauseDescriptorBlock token)).length := by
  cases token with
  | «variable» =>
      exact directSourceFinalLocalCycleRingVertexSlots_length
  | clause profile => rfl

@[simp] theorem directSourceFinalCycleRingVertexSlotValues_length
    (symbols : List encoding.Γ) :
    (directSourceFinalCycleRingVertexSlotValues decider symbols).length =
      (directSourceFinalCycleOccurrenceData decider symbols).length := by
  unfold directSourceFinalCycleRingVertexSlotValues
    directSourceFinalCycleRingVertexSlots
  rw [List.length_map,
    directSourceFinalCycleOccurrenceData_eq_clauseDescriptors]
  unfold directSourceFinalCycleClauseDescriptors
    HorizontalRoutedRouteHeaderOccurrenceBlock.output
  rw [List.flatMap_assoc]
  simp only [List.length_flatMap]
  apply congrArg List.sum
  apply List.map_congr_left
  intro token _
  simpa [HorizontalRoutedRouteHeaderOccurrenceBlock.output,
    List.length_flatMap] using
      directSourceFinalCycleRingVertexSlotBlock_length token

/-- The finite ring-slot stream is polynomial-time computable. -/
noncomputable def
    directSourceFinalCycleRingVertexSlotsComputableInPolyTime :
    TM2ComputableInPolyTime id id
      (directSourceFinalCycleRingVertexSlots decider) := by
  unfold directSourceFinalCycleRingVertexSlots
  exact TM2CompositionMachine.computableInPolyTime
    (directRetainedFigureNineFiniteSourceVariableMarkersComputableInPolyTime
      decider)
    (FiniteBlockTransducer.computableInPolyTime
      directSourceFinalCycleRingVertexSlotBlock)

/-- Numeric ring slots are polynomial-time computable as unary fields. -/
noncomputable def
    directSourceFinalCycleRingVertexSlotValuesComputableInPolyTime :
    TM2ComputableInPolyTime id UnaryFieldEncoderMachine.unaryFields
      (directSourceFinalCycleRingVertexSlotValues decider) := by
  unfold directSourceFinalCycleRingVertexSlotValues
  exact TM2CompositionMachine.computableInPolyTime
    (directSourceFinalCycleRingVertexSlotsComputableInPolyTime decider)
    (FiniteUnaryFieldMap.computableInPolyTime Fin.val)

end LeanTrominoes.PeriodicCNFStripReduction

end
