/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFClauseProfilePolarityNormalizationData

/-! # Finite route-operation schedule for polarity normalization -/

namespace LeanTrominoes
namespace PeriodicCNF
namespace ClauseProfilePolarityRouteOperation

open UnaryProgramClauseProfile
open ClauseProfilePolarityNormalization

/-- Stable source-literal positions in a nonempty width-three clause. -/
inductive SourceLiteralSlot
  | first
  | second
  | third
  deriving DecidableEq, Fintype, Inhabited

/-- The four transformations of a source incidence word introduced by
polarity normalization. -/
inductive Operation
  | compatible
  | incompatible
  | complementFresh
  | complementOriginal
  deriving DecidableEq, Fintype, Inhabited

/-- One output incidence's operation and the source incidence supplying its
word. -/
structure Descriptor where
  sourceSlot : SourceLiteralSlot
  operation : Operation
  deriving DecidableEq, Fintype, Inhabited

/-- Descriptor of one literal in the normalized copy of the source clause. -/
def normalizedDescriptor (sourceSlot : SourceLiteralSlot)
    (literalIndex : Nat) (profile : LiteralProfile) : Descriptor :=
  ⟨sourceSlot,
    if profile.value = normalizedPolarity literalIndex then
      .compatible
    else
      .incompatible⟩

/-- Optional complement clause generated by one incompatible source literal,
paired with its two exact route operations. -/
def complementRouteBlocks (sourceSlot : SourceLiteralSlot)
    (literalIndex : Nat) (profile : LiteralProfile) :
    List (ClauseProfile × List Descriptor) :=
  if profile.value = normalizedPolarity literalIndex then
    []
  else
    [(complementProfile profile,
      [⟨sourceSlot, .complementFresh⟩,
        ⟨sourceSlot, .complementOriginal⟩])]

/-- One normalized-clause block followed by one complement block for every
incompatible source literal, in the semantic clause and literal order. -/
def clauseRouteBlocks :
    ClauseProfile → List (ClauseProfile × List Descriptor)
  | .unary first =>
      [(.unary (normalizedLiteral 0 first),
        [normalizedDescriptor .first 0 first])] ++
      complementRouteBlocks .first 0 first
  | .binary first second =>
      [(.binary (normalizedLiteral 0 first)
          (normalizedLiteral 1 second),
        [normalizedDescriptor .first 0 first,
          normalizedDescriptor .second 1 second])] ++
      complementRouteBlocks .first 0 first ++
      complementRouteBlocks .second 1 second
  | .ternary first second third =>
      [(.ternary (normalizedLiteral 0 first)
          (normalizedLiteral 1 second)
          (normalizedLiteral 2 third),
        [normalizedDescriptor .first 0 first,
          normalizedDescriptor .second 1 second,
          normalizedDescriptor .third 2 third])] ++
      complementRouteBlocks .first 0 first ++
      complementRouteBlocks .second 1 second ++
      complementRouteBlocks .third 2 third

/-- Forgetting route annotations recovers the exact polarity-normalized
clause-profile block. -/
@[simp] theorem clauseRouteBlocks_map_fst (profile : ClauseProfile) :
    (clauseRouteBlocks profile).map Prod.fst = clauseProfiles profile := by
  cases profile with
  | unary first =>
      by_cases compatible : first.value = normalizedPolarity 0 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, compatible]
  | binary first second =>
      by_cases firstCompatible :
          first.value = normalizedPolarity 0 <;>
        by_cases secondCompatible :
          second.value = normalizedPolarity 1 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, firstCompatible, secondCompatible]
  | ternary first second third =>
      by_cases firstCompatible :
          first.value = normalizedPolarity 0 <;>
        by_cases secondCompatible :
          second.value = normalizedPolarity 1 <;>
        by_cases thirdCompatible :
          third.value = normalizedPolarity 2 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, firstCompatible, secondCompatible,
          thirdCompatible]

/-- Every generated clause receives exactly one descriptor per generated
literal. -/
theorem clauseRouteBlocks_lengths (profile : ClauseProfile) :
    (clauseRouteBlocks profile).map (fun block => block.2.length) =
      (clauseProfiles profile).map
        (fun generated => generated.literals.length) := by
  cases profile with
  | unary first =>
      by_cases compatible : first.value = normalizedPolarity 0 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, complementProfile, ClauseProfile.literals,
          compatible]
  | binary first second =>
      by_cases firstCompatible :
          first.value = normalizedPolarity 0 <;>
        by_cases secondCompatible :
          second.value = normalizedPolarity 1 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, complementProfile, ClauseProfile.literals,
          firstCompatible, secondCompatible]
  | ternary first second third =>
      by_cases firstCompatible :
          first.value = normalizedPolarity 0 <;>
        by_cases secondCompatible :
          second.value = normalizedPolarity 1 <;>
        by_cases thirdCompatible :
          third.value = normalizedPolarity 2 <;>
        simp [clauseRouteBlocks, complementRouteBlocks, clauseProfiles,
          complementProfiles, complementProfile, ClauseProfile.literals,
          firstCompatible, secondCompatible, thirdCompatible]

/-- Flat incidence-operation stream for one source clause profile. -/
def descriptors (profile : ClauseProfile) : List Descriptor :=
  (clauseRouteBlocks profile).flatMap Prod.snd

/-- Flat incidence-operation stream for a clause-profile sequence. -/
def stream (source : List ClauseProfile) : List Descriptor :=
  source.flatMap descriptors

end ClauseProfilePolarityRouteOperation
end PeriodicCNF
end LeanTrominoes
