import LeanTrominoes.PeriodicCNFPlanarOneInThreeNoUnitsPositioned

/-!
# Indexing the positioned unit-elimination replacement

Unit elimination is another variable-size `flatMap` of local clause blocks.
This module retains each source exact-one clause, its source presentation
index, and the local generated-clause index in a metadata list parallel to
the positioned output formula.
-/

namespace LeanTrominoes
namespace PeriodicOneInThreeNoUnitsPositioned

/-- Source and local indexing information for one clause generated by unit
elimination. -/
structure ClauseMetadata
    (Variable : Type*) where
  sourceClause : PositionedPeriodicClause Variable
  sourceClauseIndex : Nat
  clause :
    PositionedPeriodicClause
      (OneInThreeNoUnitVariable Variable)
  localClauseIndex : Nat

/-- Index every generated clause in one source clause's local replacement
block. -/
def clauseMetadataFor
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable) :
    List (ClauseMetadata Variable) :=
  (clauseGadget sourceClauseIndex sourceClause).zipIdx.map
    fun taggedClause =>
      ⟨sourceClause, sourceClauseIndex,
        taggedClause.1, taggedClause.2⟩

/-- Metadata parallel to the complete flattened positioned unit-elimination
formula. -/
def formulaClauseMetadata
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable) :
    List (ClauseMetadata Variable) :=
  source.clauses.zipIdx.flatMap fun taggedSource =>
    clauseMetadataFor taggedSource.2 taggedSource.1

@[simp]
theorem clauseMetadataFor_clauses
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable) :
    (clauseMetadataFor
      sourceClauseIndex sourceClause).map
        ClauseMetadata.clause =
      clauseGadget sourceClauseIndex sourceClause := by
  simp [clauseMetadataFor, List.map_map,
    Function.comp_def]

/-- A local metadata entry retains its source clause and genuine local
generated-clause index. -/
theorem clauseMetadataFor_valid
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable)
    {metadata : ClauseMetadata Variable}
    (metadataMember :
      metadata ∈
        clauseMetadataFor sourceClauseIndex sourceClause) :
    metadata.sourceClause = sourceClause ∧
      metadata.sourceClauseIndex = sourceClauseIndex ∧
      (metadata.clause, metadata.localClauseIndex) ∈
        (clauseGadget
          sourceClauseIndex sourceClause).zipIdx := by
  rw [clauseMetadataFor] at metadataMember
  rcases List.mem_map.mp metadataMember with
    ⟨taggedClause, taggedClauseMember,
      metadataEqual⟩
  subst metadata
  exact ⟨rfl, rfl, taggedClauseMember⟩

/-- Forgetting the indexing metadata recovers the existing positioned
unit-elimination formula. -/
@[simp]
theorem formulaClauseMetadata_clauses
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable) :
    (formulaClauseMetadata source).map
        ClauseMetadata.clause =
      (formula source).clauses := by
  simp [formulaClauseMetadata, formula,
    List.map_flatMap]

/-- Every global metadata entry retains a genuine source-clause membership
and a genuine local generated-clause membership. -/
theorem formulaClauseMetadata_valid
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {metadata : ClauseMetadata Variable}
    (metadataMember :
      metadata ∈ formulaClauseMetadata source) :
    (metadata.sourceClause,
        metadata.sourceClauseIndex) ∈
      source.clauses.zipIdx ∧
    (metadata.clause, metadata.localClauseIndex) ∈
      (clauseGadget metadata.sourceClauseIndex
        metadata.sourceClause).zipIdx := by
  rw [formulaClauseMetadata,
    List.mem_flatMap] at metadataMember
  rcases metadataMember with
    ⟨taggedSource, taggedSourceMember,
      metadataMember⟩
  have valid :=
    clauseMetadataFor_valid
      taggedSource.2 taggedSource.1 metadataMember
  constructor
  · simpa [valid.1, valid.2.1] using
      taggedSourceMember
  · simpa [valid.1, valid.2.1] using
      valid.2.2

/-- Looking up a genuine flattened output clause yields metadata carrying
that exact clause. -/
theorem formulaClauseMetadata_lookup
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {clause :
      PositionedPeriodicClause
        (OneInThreeNoUnitVariable Variable)}
    {clauseIndex : Nat}
    (clauseMember :
      (clause, clauseIndex) ∈
        (formula source).clauses.zipIdx) :
    ∃ metadata,
      (formulaClauseMetadata source)[clauseIndex]? =
        some metadata ∧
      metadata.clause = clause := by
  have clauseLookup :
      (formula source).clauses[clauseIndex]? =
        some clause :=
    (List.mem_zipIdx_iff_getElem?).mp clauseMember
  have projectedLookup :
      ((formulaClauseMetadata source).map
          ClauseMetadata.clause)[clauseIndex]? =
        some clause := by
    simpa using clauseLookup
  rw [List.getElem?_map] at projectedLookup
  simpa only [Option.map_eq_some_iff] using
    projectedLookup

/-- A genuine flattened lookup also returns both membership invariants
needed to select the corresponding certified local drawing. -/
theorem formulaClauseMetadata_lookup_valid
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {clause :
      PositionedPeriodicClause
        (OneInThreeNoUnitVariable Variable)}
    {clauseIndex : Nat}
    (clauseMember :
      (clause, clauseIndex) ∈
        (formula source).clauses.zipIdx) :
    ∃ metadata,
      (formulaClauseMetadata source)[clauseIndex]? =
        some metadata ∧
      metadata.clause = clause ∧
      (metadata.sourceClause,
          metadata.sourceClauseIndex) ∈
        source.clauses.zipIdx ∧
      (metadata.clause, metadata.localClauseIndex) ∈
        (clauseGadget metadata.sourceClauseIndex
          metadata.sourceClause).zipIdx := by
  rcases formulaClauseMetadata_lookup
      source clauseMember with
    ⟨metadata, metadataLookup, clauseEqual⟩
  have metadataIndexLt :
      clauseIndex <
        (formulaClauseMetadata source).length :=
    (List.getElem?_eq_some_iff.mp metadataLookup).1
  have metadataAt :
      (formulaClauseMetadata source)[clauseIndex] =
        metadata :=
    (List.getElem?_eq_some_iff.mp metadataLookup).2
  have metadataMember :
      metadata ∈ formulaClauseMetadata source := by
    rw [← metadataAt]
    exact List.getElem_mem metadataIndexLt
  exact
    ⟨metadata, metadataLookup, clauseEqual,
      formulaClauseMetadata_valid
        source metadataMember⟩

end PeriodicOneInThreeNoUnitsPositioned
end LeanTrominoes
