/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFClauseProfilePolarityRouteOperationData

/-! # Numeric source indices of finite polarity route operations -/

namespace LeanTrominoes
namespace PeriodicCNF
namespace ClauseProfilePolarityRouteOperation

open UnaryProgramClauseProfile
open ClauseProfilePolarityNormalization

/-- One route operation with the numeric source-literal index supplying its
word. -/
structure IndexedDescriptor where
  sourceLiteralIndex : Nat
  operation : Operation
  deriving DecidableEq, Inhabited

/-- Forget the width-three source-slot constructor while retaining its
numeric presentation index. -/
def Descriptor.indexed (descriptor : Descriptor) : IndexedDescriptor where
  sourceLiteralIndex :=
    match descriptor.sourceSlot with
    | .first => 0
    | .second => 1
    | .third => 2
  operation := descriptor.operation

/-- Numeric descriptor of a normalized main-clause occurrence. -/
def normalizedIndexedDescriptor
    (taggedValue : Bool × Nat) : IndexedDescriptor where
  sourceLiteralIndex := taggedValue.2
  operation :=
    if taggedValue.1 = normalizedPolarity taggedValue.2 then
      .compatible
    else
      .incompatible

/-- Numeric two-incidence block generated by one incompatible source
occurrence. -/
def complementIndexedDescriptorBlock
    (taggedValue : Bool × Nat) : List IndexedDescriptor :=
  if taggedValue.1 = normalizedPolarity taggedValue.2 then
    []
  else
    [⟨taggedValue.2, .complementFresh⟩,
      ⟨taggedValue.2, .complementOriginal⟩]

/-- Complete numeric operation schedule of one source clause: the main
clause first, followed by each generated complement clause. -/
def indexedDescriptors (values : List Bool) : List IndexedDescriptor :=
  values.zipIdx.map normalizedIndexedDescriptor ++
    values.zipIdx.flatMap complementIndexedDescriptorBlock

/-- The finite width-three schedule carries exactly the generic numeric
source-index/operation schedule of its literal-value list. -/
theorem descriptors_map_indexed (profile : ClauseProfile) :
    (descriptors profile).map Descriptor.indexed =
      indexedDescriptors (profile.literals.map LiteralProfile.value) := by
  cases profile <;> native_decide +revert

end ClauseProfilePolarityRouteOperation
end PeriodicCNF
end LeanTrominoes
