/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.ListZipWithExpectedFlatten
import LeanTrominoes.PeriodicCNFStripDirectSourceFinalMetadataPolarityOperationSemantics

/-! # Global source indices for direct final polarity operations -/

noncomputable section

namespace LeanTrominoes.PeriodicCNFStripReduction

open PeriodicCNF
open PeriodicCNF.ClauseProfilePolarityRouteOperation
open PeriodicOneInThreePolarityNormalizationRouteSubdivision

variable {Input : Type}
variable {encoding : _root_.Computability.FinEncoding Input}
variable {language : Input → Prop}
variable (decider : Complexity.DeciderInPolySpace encoding language)

noncomputable local instance directFinalSourceIndexedPolarityStackFintype
    (stack : decider.tm.K) : Fintype (decider.tm.Γ stack) :=
  decider.stackAlphabetFinite stack

local instance directFinalSourceIndexedPolarityVariableDecidableEq :
    DecidableEq Variable :=
  directSourceVariableDecidableEq

/-- The clause-major local polarity-operation blocks of the named direct
final gauged formula. -/
noncomputable def directSourceFinalPolarityDescriptorBlocks
    (symbols : List encoding.Γ) : List (List IndexedDescriptor) :=
  (directSourceFinalGaugedFormula decider symbols).clauses.map fun clause =>
    indexedDescriptors (clause.literals.map PeriodicLiteral.value)

/-- The global source-clause index, repeated once for every direct Figure 9
polarity route pair generated by that clause. -/
noncomputable def directFigureNinePolarityRoutePairSourceClauseIndices
    (symbols : List encoding.Γ) : List Nat :=
  (directSourceFinalPolarityDescriptorBlocks decider symbols).zipIdx.flatMap
    fun taggedBlock =>
      List.replicate taggedBlock.1.length taggedBlock.2

/-- Forgetting global clause indices from the direct operation blocks gives
exactly the local descriptors stored by the direct Figure 9 route pairs. -/
theorem directFigureNinePolarityRoutePairs_map_indexedPolarity_eq_blocks
    (symbols : List encoding.Γ) :
    (directFigureNinePolarityRoutePairs decider symbols).map
        (fun pair => pair.1.polarity.indexed) =
      (directSourceFinalPolarityDescriptorBlocks decider symbols).flatten := by
  have gaugedValueEq :=
    PositionedPeriodicCNF.variableGauge_clauseLiteralValues
      (directSourceFinalClockwiseFormula decider symbols)
      (PeriodicOrthocrossing.retainedOrderedFixedEightPeriodicPlanarOneInThreeNoUnitsFinalGauge
        (directSourceFormula decider symbols))
  have gaugedScheduleEq :=
    congrArg (List.flatMap indexedDescriptors) gaugedValueEq
  calc
    _ = (directSourceFinalClockwiseFormula decider symbols).clauses.flatMap
          (fun clause => indexedDescriptors
            (clause.literals.map PeriodicLiteral.value)) :=
      directFigureNinePolarityRoutePairs_map_indexedPolarity decider symbols
    _ = (directSourceFinalGaugedFormula decider symbols).clauses.flatMap
          (fun clause => indexedDescriptors
            (clause.literals.map PeriodicLiteral.value)) := by
      simpa only [directSourceFinalGaugedFormula,
        List.flatMap_map, Function.comp_apply] using gaugedScheduleEq.symm
    _ = _ := by
      simp only [directSourceFinalPolarityDescriptorBlocks,
        List.flatten_eq_flatMap, List.flatMap_map,
        id_eq]

/-- Attaching the explicit parent-clause index column to the direct Figure 9
pairs yields the formula's exact clause-major global operation schedule. -/
theorem directFigureNinePolarityRoutePairs_zipWith_sourceIndexedDescriptor
    (symbols : List encoding.Γ) :
    List.zipWith
        (fun sourceClauseIndex pair =>
          sourceIndexedDescriptorOf sourceClauseIndex
            pair.1.polarity.indexed)
        (directFigureNinePolarityRoutePairSourceClauseIndices decider symbols)
        (directFigureNinePolarityRoutePairs decider symbols) =
      (directSourceFinalGaugedFormula decider symbols).clauses.zipIdx.flatMap
        fun taggedClause =>
          (indexedDescriptors
            (taggedClause.1.literals.map PeriodicLiteral.value)).map
              (sourceIndexedDescriptorOf taggedClause.2) := by
  rw [← List.zipWith_map_right]
  rw [directFigureNinePolarityRoutePairs_map_indexedPolarity_eq_blocks]
  unfold directFigureNinePolarityRoutePairSourceClauseIndices
  have aligned :=
    List.zipWith_zipIdxReplicate_flatten_eq_zipIdx_flatMap_zero
      sourceIndexedDescriptorOf
      (directSourceFinalPolarityDescriptorBlocks decider symbols)
  simpa only [directSourceFinalPolarityDescriptorBlocks,
    List.zipIdx_map, List.flatMap_map, Function.comp_apply,
    Prod.map, id_eq] using aligned

end LeanTrominoes.PeriodicCNFStripReduction

end
