import LeanTrominoes.PeriodicOrthocrossingPlanarEndpoints

/-!
# SAT incidence metadata for planar routes

`PeriodicCNF.incidenceGraph` deliberately stores only graph edges.  Planar
SAT gadgets also need to recover the clause, literal sign, and literal
position that created each edge.  This file gives the same flattened
enumeration with that metadata retained and proves that its global indices
agree exactly with the incidence graph's protoedge indices.
-/

namespace LeanTrominoes

/-- One syntactic literal occurrence together with its source clause
metadata. -/
structure CNFIncidence (Variable : Type*) where
  clauseIndex : Nat
  clause : PeriodicClause Variable
  literalIndex : Nat
  literal : PeriodicLiteral Variable
  deriving DecidableEq, Repr

namespace CNFIncidence

/-- The incidence-graph protoedge generated by this literal occurrence. -/
def edge {Variable : Type*} (incidence : CNFIncidence Variable) :
    PeriodicEdge (CNFVertex Variable) :=
  PeriodicCNF.incidenceEdge incidence.clauseIndex
    (PeriodicCNF.clauseAnchor incidence.clause) incidence.literal

/-- Clause protovertex at the source of the incidence edge. -/
@[simp]
theorem edge_source {Variable : Type*}
    (incidence : CNFIncidence Variable) :
    incidence.edge.source = .clause incidence.clauseIndex := by
  rfl

/-- Variable protovertex at the target of the incidence edge. -/
@[simp]
theorem edge_target {Variable : Type*}
    (incidence : CNFIncidence Variable) :
    incidence.edge.target = .variable incidence.literal.atom := by
  rfl

/-- Target-cell offset from the clause anchor to the literal occurrence. -/
@[simp]
theorem edge_offset {Variable : Type*}
    (incidence : CNFIncidence Variable) :
    incidence.edge.offset =
      Cell.sub incidence.literal.offset
        (PeriodicCNF.clauseAnchor incidence.clause) := by
  rfl

end CNFIncidence

namespace PeriodicCNF

/-- All syntactic literal incidences in clause-major, literal-minor order. -/
def incidencesWithMetadata {Variable : Type*}
    (formula : PeriodicCNF Variable) : List (CNFIncidence Variable) :=
  formula.clauses.zipIdx.flatMap fun taggedClause =>
    taggedClause.1.zipIdx.map fun taggedLiteral =>
      ⟨taggedClause.2, taggedClause.1,
        taggedLiteral.2, taggedLiteral.1⟩

/-- Forgetting the metadata yields exactly the protoedge presentation used
by `incidenceGraph`, in the same order. -/
theorem incidencesWithMetadata_edges
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    (incidencesWithMetadata formula).map CNFIncidence.edge =
      (incidenceGraph formula).edges := by
  unfold incidencesWithMetadata incidenceGraph
  simp only [List.map_flatMap, clauseIncidenceEdges]
  apply List.flatMap_congr
  intro taggedClause taggedClauseMem
  calc
    (taggedClause.1.zipIdx.map
        (fun taggedLiteral =>
          (⟨taggedClause.2, taggedClause.1,
            taggedLiteral.2, taggedLiteral.1⟩ :
              CNFIncidence Variable))).map CNFIncidence.edge =
        (taggedClause.1.zipIdx.map Prod.fst).map
          (PeriodicCNF.incidenceEdge taggedClause.2
            (PeriodicCNF.clauseAnchor taggedClause.1)) := by
              rw [List.map_map, List.map_map]
              rfl
    _ = taggedClause.1.map
          (PeriodicCNF.incidenceEdge taggedClause.2
            (PeriodicCNF.clauseAnchor taggedClause.1)) := by
              rw [List.zipIdx_map_fst]

/-- A metadata occurrence and its global flattened index name the matching
tagged protoedge. -/
theorem tagged_incidence_edge_mem
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    {tagged : CNFIncidence Variable × Nat}
    (taggedMem : tagged ∈ (incidencesWithMetadata formula).zipIdx) :
    (tagged.1.edge, tagged.2) ∈
      (incidenceGraph formula).edges.zipIdx := by
  rw [← incidencesWithMetadata_edges formula, List.zipIdx_map]
  exact List.mem_map.mpr
    ⟨tagged, taggedMem, by cases tagged; rfl⟩

end PeriodicCNF

namespace PeriodicOrthocrossing

/-- One translated routed occurrence of a syntactic CNF incidence. -/
structure CNFRouteOccurrence (Variable : Type*) where
  incidence : CNFIncidence Variable
  edgeIndex : Nat
  translate : Cell
  deriving DecidableEq, Repr

/-- The protoedge routed by a CNF occurrence. -/
def CNFRouteOccurrence.edge {Variable : Type*}
    (occurrence : CNFRouteOccurrence Variable) :
    PeriodicEdge (CNFVertex Variable) :=
  occurrence.incidence.edge

/-- Its translated-route key. -/
def CNFRouteOccurrence.routeKey {Variable : Type*}
    (occurrence : CNFRouteOccurrence Variable) :
    RouteOccurrenceKey :=
  (occurrence.edgeIndex, occurrence.translate)

/-- The lifted clause vertex at the source of the route. -/
def CNFRouteOccurrence.clauseOccurrence {Variable : Type*}
    (occurrence : CNFRouteOccurrence Variable) : Nat × Cell :=
  (occurrence.incidence.clauseIndex, occurrence.translate)

/-- The lifted variable vertex at the target of the route. -/
def CNFRouteOccurrence.variableOccurrence {Variable : Type*}
    (occurrence : CNFRouteOccurrence Variable) : Variable × Cell :=
  (occurrence.incidence.literal.atom,
    Cell.add occurrence.translate occurrence.edge.offset)

/-- Every neighboring translated occurrence of every metadata-rich
incidence edge. -/
def drawingCNFRouteOccurrences
    {Variable : Type*} (formula : PeriodicCNF Variable) :
    List (CNFRouteOccurrence Variable) :=
  (PeriodicCNF.incidencesWithMetadata formula).zipIdx.flatMap
    fun taggedIncidence =>
      neighborTranslations.map fun translate =>
        ⟨taggedIncidence.1, taggedIncidence.2, translate⟩

/-- A routed endpoint paired with the SAT incidence metadata that created
its protoedge. -/
structure CNFRouteEndpoint (Variable : Type*) where
  occurrence : CNFRouteOccurrence Variable
  endpoint : RouteEndpoint (CNFVertex Variable)
  deriving DecidableEq, Repr

/-- Both geometric endpoints of one routed CNF incidence occurrence. -/
def CNFRouteOccurrence.endpoints
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (occurrence : CNFRouteOccurrence Variable) :
    List (CNFRouteEndpoint Variable) :=
  let graph := PeriodicCNF.incidenceGraph formula
  (translatedEdgeRouteEndpoints graph
      (occurrence.edge, occurrence.edgeIndex)
      occurrence.translate).map fun endpoint =>
    ⟨occurrence, endpoint⟩

/-- All metadata-rich route endpoints in the neighboring block. -/
def drawingCNFRouteEndpoints
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    List (CNFRouteEndpoint Variable) :=
  (drawingCNFRouteOccurrences formula).flatMap
    fun occurrence => occurrence.endpoints formula

/-- Every metadata-rich route occurrence has its source and target endpoint. -/
theorem CNFRouteOccurrence.endpoints_length
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (occurrence : CNFRouteOccurrence Variable) :
    (occurrence.endpoints formula).length = 2 := by
  simp only [CNFRouteOccurrence.endpoints, List.length_map]
  exact translatedEdgeRouteEndpoints_length
    (PeriodicCNF.incidenceGraph formula)
    (occurrence.edge, occurrence.edgeIndex)
    occurrence.translate

/-- The endpoint terminal retains its metadata occurrence's route key. -/
theorem CNFRouteEndpoint.terminal_routeKey
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    {routeEndpoint : CNFRouteEndpoint Variable}
    (endpointMem :
      routeEndpoint ∈
        routeEndpoint.occurrence.endpoints formula) :
    routeEndpoint.endpoint.terminal.routeKey =
      routeEndpoint.occurrence.routeKey := by
  simp only [CNFRouteOccurrence.endpoints, List.mem_map] at endpointMem
  rcases endpointMem with ⟨endpoint, endpointMem, endpointEq⟩
  have endpointFieldEq :
      endpoint = routeEndpoint.endpoint :=
    congrArg CNFRouteEndpoint.endpoint endpointEq
  rw [← endpointFieldEq]
  have terminalKey :=
    routeEndpointsFromSegments_terminal_routeKey
      routeEndpoint.occurrence.edge
      routeEndpoint.occurrence.edgeIndex
      routeEndpoint.occurrence.translate
      (gridPolylineSegments
        (constructedEdgeRoute
          (PeriodicCNF.incidenceGraph formula)
          routeEndpoint.occurrence.edge
          routeEndpoint.occurrence.edgeIndex)).zipIdx
      endpointMem
  have endpointKey :=
    routeEndpointsFromSegments_routeKey
      routeEndpoint.occurrence.edge
      routeEndpoint.occurrence.edgeIndex
      routeEndpoint.occurrence.translate
      (gridPolylineSegments
        (constructedEdgeRoute
          (PeriodicCNF.incidenceGraph formula)
          routeEndpoint.occurrence.edge
          routeEndpoint.occurrence.edgeIndex)).zipIdx
      endpointMem
  exact terminalKey.trans endpointKey

end PeriodicOrthocrossing
end LeanTrominoes
