/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicThreeDMNormalizationStripOrientationEvaluation

/-!
# Membership constructors for normalized 3DM strip orientation sites
-/

namespace LeanTrominoes

namespace PeriodicThreeDM

/-- Strip provenance generated by a suffix of at least three points also
occurs after prepending any route prefix. -/
theorem stripRouteOrientationSites_subset_append
    (period : Nat) (edge : ContractedEdge)
    (leading suffix : List Cell)
    (suffixLength : 3 ≤ suffix.length) :
    ∀ entry,
      entry ∈ stripRouteOrientationSites period edge suffix →
      entry ∈ stripRouteOrientationSites period edge (leading ++ suffix) := by
  induction leading with
  | nil =>
      intro entry member
      simpa using member
  | cons first leading induction =>
      intro entry member
      cases leading with
      | nil =>
          obtain ⟨suffixFirst, suffixSecond, suffixThird, suffixRest,
              suffixEquation⟩ :=
            List.exists_eq_cons_cons_cons_of_length_ge_three suffixLength
          rw [suffixEquation] at member ⊢
          simp only [List.cons_append, List.nil_append]
          rw [stripRouteOrientationSites]
          exact List.mem_cons_of_mem _ member
      | cons second leading =>
          have recursive := induction entry member
          obtain ⟨after, remainder, tailEquation⟩ :
              ∃ after remainder,
                leading ++ suffix = after :: remainder := by
            cases leading with
            | nil =>
                obtain ⟨suffixFirst, suffixSecond, suffixThird, suffixRest,
                    suffixEquation⟩ :=
                  List.exists_eq_cons_cons_cons_of_length_ge_three suffixLength
                rw [suffixEquation]
                exact ⟨suffixFirst,
                  suffixSecond :: suffixThird :: suffixRest, rfl⟩
            | cons after remainder => exact ⟨after, remainder ++ suffix, rfl⟩
          change entry ∈ stripRouteOrientationSites period edge
            (second :: (leading ++ suffix)) at recursive
          rw [tailEquation] at recursive
          change entry ∈ stripRouteOrientationSites period edge
            (first :: second :: (leading ++ suffix))
          rw [tailEquation]
          rw [stripRouteOrientationSites]
          exact List.mem_cons_of_mem _ recursive

/-- A displayed route triple contributes its strip provenance entry. -/
theorem stripRouteOrientationSite_mem_append
    (period : Nat) (edge : ContractedEdge)
    (leading : List Cell) (before current after : Cell)
    (rest : List Cell) :
    (stripRasterLocation period current,
      FinalOrientationSite.route edge before current after) ∈
      stripRouteOrientationSites period edge
        (leading ++ before :: current :: after :: rest) := by
  let suffix := before :: current :: after :: rest
  have suffixLength : 3 ≤ suffix.length := by simp [suffix]
  have suffixMember :
      (stripRasterLocation period current,
        FinalOrientationSite.route edge before current after) ∈
        stripRouteOrientationSites period edge suffix := by
    simp [suffix, stripRouteOrientationSites]
  exact stripRouteOrientationSites_subset_append period edge leading suffix
    suffixLength _ suffixMember

/-- Every listed normalized vertex contributes a strip provenance site. -/
theorem PlanarPresentation.finalStripOrientationSite_vertex_mem
    {problem : PeriodicThreeDM}
    (presentation : problem.PlanarPresentation)
    {vertex : PeriodicThreeDMVertex}
    (member : vertex ∈ problem.contractedGraph.vertices) :
    (stripRasterLocation presentation.finalNormalizationPeriod
        (presentation.finalNormalizationPosition vertex),
      FinalOrientationSite.vertex vertex) ∈
      presentation.finalStripOrientationSites := by
  unfold PlanarPresentation.finalStripOrientationSites
  simp only [List.mem_append]
  left
  exact List.mem_map.mpr ⟨vertex, member, rfl⟩

/-- Every displayed triple of a listed normalized edge contributes its strip
route provenance site. -/
theorem PlanarPresentation.finalStripOrientationSite_route_mem
    {problem : PeriodicThreeDM}
    (presentation : problem.PlanarPresentation)
    {edge : ContractedEdge}
    (edgeMember : edge ∈ problem.contractedEdges)
    (leading : List Cell) (before current after : Cell) (rest : List Cell)
    (routeEquation : presentation.finalNormalizationRoute edge =
      leading ++ before :: current :: after :: rest) :
    (stripRasterLocation presentation.finalNormalizationPeriod current,
      FinalOrientationSite.route edge before current after) ∈
      presentation.finalStripOrientationSites := by
  unfold PlanarPresentation.finalStripOrientationSites
  simp only [List.mem_append]
  right
  simp only [List.mem_flatMap]
  refine ⟨edge, edgeMember, ?_⟩
  rw [routeEquation]
  exact stripRouteOrientationSite_mem_append _ _ _ _ _ _ _

end PeriodicThreeDM
end LeanTrominoes
