/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFStripDirectSourceFormulaData

/-! # Normal form of direct strip source formulas -/

noncomputable section

namespace LeanTrominoes.PeriodicCNFStripReduction

open PeriodicCNF

variable {Input : Type}
variable {encoding : _root_.Computability.FinEncoding Input}
variable {language : Input → Prop}
variable (decider : Complexity.DeciderInPolySpace encoding language)

noncomputable local instance directSourceNormalizedFormulaStackFintype
    (stack : decider.tm.K) : Fintype (decider.tm.Γ stack) :=
  decider.stackAlphabetFinite stack

/-- The guarded direct source always takes the ordinary occurrence-splitting
branch on formulas generated by the PSPACE compiler. -/
theorem directSourceFormula_eq_threeSATThree
    (symbols : List encoding.Γ) :
    directSourceFormula decider symbols =
      PeriodicThreeSATThree.formula
        (PeriodicThreeCNF.formula
          (PolySpaceCompiler.formulaOfSymbols decider symbols)) := by
  unfold directSourceFormula
  rw [sourceFormula_formulaOfSymbols]
  rfl

end LeanTrominoes.PeriodicCNFStripReduction
