/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.FiniteBlockTransducer
import LeanTrominoes.PeriodicCNFStripHorizontalRoutedRouteHeaderOccurrenceSemantics

/-! # Parent-clause blocks of finite routed-header occurrence data -/

noncomputable section

namespace LeanTrominoes
namespace PeriodicCNFStripReduction
namespace HorizontalRoutedRouteHeaderOccurrenceBlock

open Computability Turing
open PeriodicCNF.FormulaShapeDirectionOrdering
open PeriodicCNF.FormulaShapeFigureNinePolarityRouteHeader

abbrev InputToken := PeriodicCNF.FormulaShapeDirectionOrdering.Token
abbrev OccurrenceData := HorizontalRoutedRouteHeader.OccurrenceData

/-- All final Figure 9 occurrence data generated by one parent descriptor. -/
def tokenBlock : InputToken → List OccurrenceData
  | .clause profile =>
      (sourceClauseHeaders profile).map
        HorizontalRoutedRouteHeader.occurrenceData
  | .variable => []

/-- Concatenated copied-clause occurrence data, retaining parent-block order. -/
def output (source : List InputToken) : List OccurrenceData :=
  source.flatMap tokenBlock

/-- Parent descriptors expand to finite occurrence blocks in linear time. -/
noncomputable def computableInPolyTime :
    TM2ComputableInPolyTime id id output :=
  FiniteBlockTransducer.computableInPolyTime tokenBlock

/-- Parent-relative atom-equality square of one expanded descriptor. -/
def atomEqualityBlock : InputToken → List Bool
  | .clause profile =>
      let headers := sourceClauseHeaders profile
      (headers.product headers).map fun pair =>
        (HorizontalRoutedRouteHeader.outputAtomControl pair.1).sameAtom
          (HorizontalRoutedRouteHeader.outputAtomControl pair.2)
  | .variable => []

/-- One bounded parent-relative equality square per copied source clause. -/
def atomEqualityBits (source : List InputToken) : List Bool :=
  source.flatMap atomEqualityBlock

/-- All block-local final-atom equality squares are polynomial-time. -/
noncomputable def atomEqualityBitsComputableInPolyTime :
    TM2ComputableInPolyTime id id atomEqualityBits :=
  FiniteBlockTransducer.computableInPolyTime atomEqualityBlock

/-- Equality square of the explicit parent-relative atoms represented by one
source descriptor. -/
def representedAtomEqualityBlock : InputToken → List Bool
  | .clause profile =>
      let headers := sourceClauseHeaders profile
      (headers.product headers).map fun pair =>
        decide
          (HorizontalRoutedRouteHeader.outputParentRelativeAtom pair.1 =
            HorizontalRoutedRouteHeader.outputParentRelativeAtom pair.2)
  | .variable => []

/-- Every block-local Boolean square is exactly equality of the represented
parent-relative final atoms. -/
theorem atomEqualityBlock_eq (token : InputToken) :
    atomEqualityBlock token =
      representedAtomEqualityBlock token := by
  cases token with
  | «variable» => rfl
  | clause profile =>
      simp only [atomEqualityBlock, representedAtomEqualityBlock]
      apply List.map_congr_left
      intro pair _
      exact HorizontalRoutedRouteHeader.outputAtomControl_sameAtom
        pair.1 pair.2

@[simp] theorem tokenBlock_clause (profile : DirectedClauseProfile) :
    tokenBlock (.clause profile) =
      (sourceClauseHeaders profile).map
        HorizontalRoutedRouteHeader.occurrenceData :=
  rfl

@[simp] theorem tokenBlock_variable : tokenBlock .variable = [] :=
  rfl

end HorizontalRoutedRouteHeaderOccurrenceBlock
end PeriodicCNFStripReduction
end LeanTrominoes

end
