/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFStripHorizontalRoutedRouteHeaderPresentationAtomScopeCompiler

/-! # Local final-atom occurrence bounds in one routed parent block -/

namespace LeanTrominoes
namespace PeriodicCNFStripReduction
namespace HorizontalRoutedRouteHeaderPresentationAtomScope

open PeriodicCNF.FormulaShapeDirectionOrdering
open HorizontalRoutedRouteHeader

/-- Represented parent-relative atoms at the parent-local positions of one
final routed block. -/
def parentLocalAtoms (profile : DirectedClauseProfile) :
    List ParentRelativeAtom :=
  (clauseBlock profile).filterMap fun scope =>
    match scope with
    | .inherited _ => none
    | .parentLocal control => some control.representedAtom

/-- As above, the checker scans only atoms that occur in its finite block. -/
private theorem parentLocalAtoms_count_check
    (profile : DirectedClauseProfile) :
    (parentLocalAtoms profile).all fun atom =>
      decide ((parentLocalAtoms profile).count atom <= 3) := by
  cases profile <;> native_decide +revert

/-- Quotienting the several descriptors that can represent the same local
atom still leaves multiplicity at most three. -/
theorem parentLocalAtoms_count_le_three
    (profile : DirectedClauseProfile) (atom : ParentRelativeAtom) :
    (parentLocalAtoms profile).count atom <= 3 := by
  by_cases member : atom ∈ parentLocalAtoms profile
  · have checked :=
      (List.all_eq_true.mp (parentLocalAtoms_count_check profile))
        atom member
    simpa only [decide_eq_true_eq] using checked
  · rw [List.count_eq_zero_of_not_mem member]
    omega

/-- The finite checker only scans controls that actually occur in the
selected block.  This avoids enumerating the much larger ambient descriptor
alphabet. -/
private theorem clauseBlock_local_count_check
    (profile : DirectedClauseProfile) :
    (clauseBlock profile).all fun scope =>
      match scope with
      | .inherited _ => true
      | .parentLocal control =>
          decide
            ((clauseBlock profile).count (.parentLocal control) <= 3) := by
  cases profile <;> native_decide +revert

/-- Every parent-local Figure 9 or polarity-normalization atom occurs at most
three times in the final routed block generated by one source clause. -/
theorem clauseBlock_count_parentLocal_le_three
    (profile : DirectedClauseProfile) (control : AtomControl) :
    (clauseBlock profile).count (.parentLocal control) <= 3 := by
  by_cases member :
      AtomScopeControl.parentLocal control ∈ clauseBlock profile
  · have checked :=
      (List.all_eq_true.mp (clauseBlock_local_count_check profile))
        (.parentLocal control) member
    simpa only [decide_eq_true_eq] using checked
  · rw [List.count_eq_zero_of_not_mem member]
    omega

end HorizontalRoutedRouteHeaderPresentationAtomScope
end PeriodicCNFStripReduction
end LeanTrominoes
