/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFStripHorizontalRoutedRouteHeaderOccurrenceData

/-! # Clause semantics of finite routed-header occurrence fields -/

namespace LeanTrominoes
namespace PeriodicCNFStripReduction
namespace HorizontalRoutedRouteHeader

open PlanarThreeDM
open PeriodicCNF
open PeriodicCNF.ClauseProfilePolarityNormalization
open PeriodicCNF.ClauseProfilePolarityRouteOperation
open PeriodicCNF.FormulaShapeFigureNinePolarityRouteHeader
open PeriodicCNF.FormulaShapeFigureNineRoutePrefix
open PeriodicCNF.UnaryProgramClauseProfile

/-- Output literal position determined by one polarity descriptor, before it
is paired with the finite Figure 9 prefix. -/
def descriptorOutputLiteralIndex
    (descriptor : ClauseProfilePolarityRouteOperation.Descriptor) : Nat :=
  match descriptor.operation with
  | .compatible | .incompatible => sourceSlotNat descriptor.sourceSlot
  | .complementFresh => 0
  | .complementOriginal => 1

def descriptorOutputConnectorKind
    (descriptor : ClauseProfilePolarityRouteOperation.Descriptor) :
    VariableConnectorKind :=
  PeriodicPlanarOneInThreeToThreeDM.connectorKindOfLiteralIndex
    (descriptorOutputLiteralIndex descriptor)

def descriptorOutputPolarity
    (descriptor : ClauseProfilePolarityRouteOperation.Descriptor) : Bool :=
  normalizedPolarity (descriptorOutputLiteralIndex descriptor)

@[simp] theorem outputLiteralIndex_eq_descriptor (header : Header) :
    outputLiteralIndex header =
      descriptorOutputLiteralIndex header.polarity := by
  rfl

@[simp] theorem outputConnectorKind_eq_descriptor (header : Header) :
    outputConnectorKind header =
      descriptorOutputConnectorKind header.polarity := by
  rfl

@[simp] theorem outputPolarity_eq_descriptor (header : Header) :
    outputPolarity header = descriptorOutputPolarity header.polarity := by
  rfl

/-- Explicit final variable represented by a header, relative to its parent
source clause.  The right summand is the occurrence-local fresh-variable
tag; the left summand is the selected finite Figure 9 atom. -/
abbrev ParentRelativeAtom :=
  Sum PlanarOneInThreeNoUnitsFigureNine.FigureNineNoUnitsVariable
    PrefixDescriptor

def outputParentRelativeAtom (header : Header) : ParentRelativeAtom :=
  match header.polarity.operation with
  | .compatible | .complementOriginal =>
      .inl (prefixAtom header.figurePrefix)
  | .incompatible | .complementFresh =>
      .inr header.figurePrefix

/-- The finite atom-control comparator is exactly equality of the represented
parent-relative final variables. -/
theorem outputAtomControl_sameAtom (first second : Header) :
    (outputAtomControl first).sameAtom (outputAtomControl second) =
      decide
        (outputParentRelativeAtom first = outputParentRelativeAtom second) := by
  rcases first with ⟨⟨firstSlot, firstOperation⟩, firstPrefix⟩
  rcases second with ⟨⟨secondSlot, secondOperation⟩, secondPrefix⟩
  cases firstOperation <;> cases secondOperation <;>
    simp [outputAtomControl, AtomControl.sameAtom,
      outputParentRelativeAtom]

/-- Connector-kind fields of a finite clause profile in literal order. -/
def clauseConnectorKinds (profile : ClauseProfile) :
    List VariableConnectorKind :=
  profile.literals.zipIdx.map fun tagged =>
    PeriodicPlanarOneInThreeToThreeDM.connectorKindOfLiteralIndex tagged.2

/-- Polarity fields of a finite clause profile in literal order. -/
def clausePolarities (profile : ClauseProfile) : List Bool :=
  profile.literals.map LiteralProfile.value

/-- The polarity-operation schedule carries exactly the connector kinds of
the generated normalized and complement clauses. -/
theorem descriptors_map_outputConnectorKind (profile : ClauseProfile) :
    (ClauseProfilePolarityRouteOperation.descriptors profile).map
        descriptorOutputConnectorKind =
      (clauseProfiles profile).flatMap clauseConnectorKinds := by
  cases profile <;> native_decide +revert

/-- The polarity-operation schedule carries exactly the literal polarities
of the generated normalized and complement clauses. -/
theorem descriptors_map_outputPolarity (profile : ClauseProfile) :
    (ClauseProfilePolarityRouteOperation.descriptors profile).map
        descriptorOutputPolarity =
      (clauseProfiles profile).flatMap clausePolarities := by
  cases profile <;> native_decide +revert

/-- Figure 9 headers expose the exact connector-kind stream of the final
polarity-normalized clauses generated by one directed source clause. -/
theorem sourceClauseHeaders_map_outputConnectorKind
    (profile : FormulaShapeDirectionOrdering.DirectedClauseProfile) :
    (sourceClauseHeaders profile).map outputConnectorKind =
      (figureClauseProfiles (orderedDirectedProfile profile)).flatMap
        (fun clauseProfile =>
          (clauseProfiles clauseProfile).flatMap clauseConnectorKinds) := by
  rw [show (sourceClauseHeaders profile).map outputConnectorKind =
      ((sourceClauseHeaders profile).map Header.polarity).map
        descriptorOutputConnectorKind by
      rw [List.map_map]
      rfl]
  rw [sourceClauseHeaders_map_polarity, List.map_flatMap]
  apply List.flatMap_congr
  intro clauseProfile _
  exact descriptors_map_outputConnectorKind clauseProfile

/-- Figure 9 headers expose the exact polarity stream of the final
polarity-normalized clauses generated by one directed source clause. -/
theorem sourceClauseHeaders_map_outputPolarity
    (profile : FormulaShapeDirectionOrdering.DirectedClauseProfile) :
    (sourceClauseHeaders profile).map outputPolarity =
      (figureClauseProfiles (orderedDirectedProfile profile)).flatMap
        (fun clauseProfile =>
          (clauseProfiles clauseProfile).flatMap clausePolarities) := by
  rw [show (sourceClauseHeaders profile).map outputPolarity =
      ((sourceClauseHeaders profile).map Header.polarity).map
        descriptorOutputPolarity by
      rw [List.map_map]
      rfl]
  rw [sourceClauseHeaders_map_polarity, List.map_flatMap]
  apply List.flatMap_congr
  intro clauseProfile _
  exact descriptors_map_outputPolarity clauseProfile

end HorizontalRoutedRouteHeader
end PeriodicCNFStripReduction
end LeanTrominoes
