import LeanTrominoes.PeriodicOneInThreePolarityNormalizationRibbonReadyPresentation
import LeanTrominoes.PeriodicOneInThreePolarityNormalizationRouteOrders
import LeanTrominoes.PeriodicOneInThreePolarityNormalizationVariableRouteOrder
import LeanTrominoes.PeriodicPlanarOneInThreeToThreeDMRibbonPaddedContinuousPresentation

/-!
# Polarity-normalized ribbon reduction to planar periodic 3DM

The routed polarity normalization now supplies every premise of the padded
three-strand 3DM assembly.  This file packages that composition and records
the target's structural promises and exact orientation semantics.
-/

namespace LeanTrominoes
namespace PeriodicOneInThreePolarityNormalizationRouteSubdivision

set_option maxHeartbeats 2000000

/-- Read the normalized occurrence bound using the canonical Boolean equality
generated by its `DecidableEq` instance, as expected by the 3DM interface. -/
private theorem formula_occurrencesAtMostThree_canonicalBEq
    {Variable : Type*} [DecidableEq Variable]
    (source : PositionedPeriodicCNF Variable)
    (sourcePlacement : PeriodicVariablePlacement Variable)
    (sourceRoutes : PositionedPeriodicCNF.IncidenceRoutes)
    (occurrences : source.erase.OccurrencesAtMost 3) :
    @PeriodicCNF.OccurrencesAtMost
      (PolarityNormalizedVariable Variable) instBEqOfDecidableEq
      (by infer_instance) 3
      (formula source sourcePlacement sourceRoutes).erase := by
  exact PeriodicCNF.occurrencesAtMost_congr_beq
    _ _ (by infer_instance) (by infer_instance) 3
    (formula source sourcePlacement sourceRoutes).erase
    (formula_occurrencesAtMostThree
      source sourcePlacement sourceRoutes occurrences)

/-- The padded encoded 3DM target built from the routed polarity-normalized
source. -/
noncomputable def paddedPeriodicThreeDMProblem
    {Variable : Type*} [DecidableEq Variable]
    (source : PositionedPeriodicCNF Variable)
    (sourcePlacement : PeriodicVariablePlacement Variable)
    (sourceRoutes : PositionedPeriodicCNF.IncidenceRoutes) :
    PeriodicThreeDM :=
  PeriodicPlanarOneInThreeToThreeDM.normalizedProblem
    ((formula source sourcePlacement sourceRoutes).scale 2)
    ((placement sourcePlacement sourceRoutes).scale 2)

/-- Every reference in the polarity-normalized padded 3DM target names a
declared colored element. -/
theorem paddedPeriodicThreeDMProblem_isWellFormed
    {Variable : Type*} [DecidableEq Variable]
    (source : PositionedPeriodicCNF Variable)
    (sourcePlacement : PeriodicVariablePlacement Variable)
    (sourceRoutes : PositionedPeriodicCNF.IncidenceRoutes) :
    (paddedPeriodicThreeDMProblem
      source sourcePlacement sourceRoutes).IsWellFormed := by
  exact
    PeriodicPlanarOneInThreeToThreeDM.normalizedProblem_isWellFormed
      ((formula source sourcePlacement sourceRoutes).scale 2)
      ((placement sourcePlacement sourceRoutes).scale 2)

/-- The polarity-normalized padded target retains the promised colored
degree-two-or-three bound. -/
theorem paddedPeriodicThreeDMProblem_degreeTwoOrThree
    {Variable : Type*} [DecidableEq Variable]
    (source : PositionedPeriodicCNF Variable)
    (sourcePlacement : PeriodicVariablePlacement Variable)
    (sourceRoutes : PositionedPeriodicCNF.IncidenceRoutes)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase) :
    (paddedPeriodicThreeDMProblem
      source sourcePlacement sourceRoutes).DegreeTwoOrThree := by
  apply
    PeriodicPlanarOneInThreeToThreeDM.normalizedProblem_degreeTwoOrThree
  · simpa using
      formula_occurrencesAtMostThree_canonicalBEq
        source sourcePlacement sourceRoutes occurrences
  · simpa using
      formula_arityTwoOrThree source sourcePlacement sourceRoutes arity

/-- The padded target admits a graph orientation exactly when the original
positioned exact-one source is satisfiable. -/
theorem paddedPeriodicThreeDMProblem_graphHasOrientation_iff
    {Variable : Type*} [DecidableEq Variable]
    (source : PositionedPeriodicCNF Variable)
    (sourcePlacement : PeriodicVariablePlacement Variable)
    (sourceRoutes : PositionedPeriodicCNF.IncidenceRoutes)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase) :
    (paddedPeriodicThreeDMProblem
        source sourcePlacement sourceRoutes).GraphHasOrientation ↔
      PeriodicOneInThree.Satisfiable source.erase := by
  have normalizedOccurrences :
      @PeriodicCNF.OccurrencesAtMost
        (PolarityNormalizedVariable Variable) instBEqOfDecidableEq
        (by infer_instance) 3
        ((formula source sourcePlacement sourceRoutes).scale 2).erase := by
    simpa using formula_occurrencesAtMostThree_canonicalBEq
      source sourcePlacement sourceRoutes occurrences
  have normalizedArity :
      PeriodicOneInThreeNoUnits.ArityTwoOrThree
        ((formula source sourcePlacement sourceRoutes).scale 2).erase := by
    simpa using
      formula_arityTwoOrThree source sourcePlacement sourceRoutes arity
  have normalizedIff :=
    PeriodicPlanarOneInThreeToThreeDM.normalizedProblem_graphHasOrientation_iff_source
      ((formula source sourcePlacement sourceRoutes).scale 2)
      ((placement sourcePlacement sourceRoutes).scale 2)
      normalizedOccurrences normalizedArity
  have routedIff := satisfiable_iff source sourcePlacement sourceRoutes
  have normalizedIff' :
      (paddedPeriodicThreeDMProblem
          source sourcePlacement sourceRoutes).GraphHasOrientation ↔
        PeriodicOneInThree.Satisfiable
          (formula source sourcePlacement sourceRoutes).erase := by
    simpa [paddedPeriodicThreeDMProblem] using normalizedIff
  exact normalizedIff'.trans routedIff

/-- A ribbon-ready ordered source produces a concrete continuously planar
presentation of its polarity-normalized padded 3DM target. -/
noncomputable def paddedPeriodicThreeDMContinuousPlanarPresentation
    {Variable : Type*} [DecidableEq Variable]
    {source : PositionedPeriodicCNF Variable}
    {sourcePlacement : PeriodicVariablePlacement Variable}
    (presentation :
      PositionedPeriodicCNF.HaloBoundedRibbonReadyIncidencePresentation
        source sourcePlacement)
    (sourceUnitSteps :
      (PositionedPeriodicCNF.incidenceDrawing
        source sourcePlacement presentation.routes).HasUnitSteps)
    (sourceDistinct : source.AllAtomsNodup)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase)
    (variableOrdered :
      source.VariableRoutesInOccurrenceOrder presentation.routes)
    (clauseOrdered :
      source.TernaryClauseRoutesInClockwiseOrder presentation.routes) :
    (paddedPeriodicThreeDMProblem
      source sourcePlacement presentation.routes).ContinuousPlanarPresentation := by
  let normalizedPresentation :=
    haloBoundedRibbonReadyPresentation presentation sourceUnitSteps
  exact
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedContinuousPlanarPresentation
      normalizedPresentation
      (formula_widthAtMostThree
        source sourcePlacement presentation.routes arity)
      (formula_polarityNormalized
        source sourcePlacement presentation.routes)
      (formula_occurrencesAtMostThree_canonicalBEq
        source sourcePlacement presentation.routes occurrences)
      (formula_arityTwoOrThree
        source sourcePlacement presentation.routes arity)
      (incidenceRoutes_variableRoutesInOccurrenceOrder
        presentation.toContinuousPlanarIncidencePresentation
        sourceDistinct variableOrdered)
      (incidenceRoutes_ternaryClauseRoutesInClockwiseOrder
        presentation.toContinuousPlanarIncidencePresentation clauseOrdered)

/-- The final padded drawing's stored segment endpoints lie in the open
one-cell halo used by the finite periodic planarity checks. -/
theorem paddedPeriodicThreeDMContinuousPlanarPresentation_endpointBounds
    {Variable : Type*} [DecidableEq Variable]
    {source : PositionedPeriodicCNF Variable}
    {sourcePlacement : PeriodicVariablePlacement Variable}
    (presentation :
      PositionedPeriodicCNF.HaloBoundedRibbonReadyIncidencePresentation
        source sourcePlacement)
    (sourceUnitSteps :
      (PositionedPeriodicCNF.incidenceDrawing
        source sourcePlacement presentation.routes).HasUnitSteps)
    (sourceDistinct : source.AllAtomsNodup)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase)
    (variableOrdered :
      source.VariableRoutesInOccurrenceOrder presentation.routes)
    (clauseOrdered :
      source.TernaryClauseRoutesInClockwiseOrder presentation.routes) :
    (paddedPeriodicThreeDMContinuousPlanarPresentation
      presentation sourceUnitSteps sourceDistinct occurrences arity
      variableOrdered clauseOrdered).drawing
        |>.SegmentEndpointsInExpandedSquare := by
  let normalizedPresentation :=
    haloBoundedRibbonReadyPresentation presentation sourceUnitSteps
  change
    (PeriodicPlanarOneInThreeToThreeDM.assembledDrawing
      (PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedRibbonThreeStrandRouting
        normalizedPresentation
        (formula_widthAtMostThree
          source sourcePlacement presentation.routes arity)
        (formula_occurrencesAtMostThree_canonicalBEq
          source sourcePlacement presentation.routes occurrences)
        (formula_arityTwoOrThree
          source sourcePlacement presentation.routes arity)
        (incidenceRoutes_variableRoutesInOccurrenceOrder
          presentation.toContinuousPlanarIncidencePresentation
          sourceDistinct variableOrdered)
        (incidenceRoutes_ternaryClauseRoutesInClockwiseOrder
          presentation.toContinuousPlanarIncidencePresentation clauseOrdered)))
      |>.SegmentEndpointsInExpandedSquare
  apply
    PeriodicGridDrawing.segmentEndpointsInExpandedSquare_of_routePoints
  exact
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedAssembledRoutePointsInExpandedSquare
      normalizedPresentation
      (formula_widthAtMostThree
        source sourcePlacement presentation.routes arity)
      (formula_occurrencesAtMostThree_canonicalBEq
        source sourcePlacement presentation.routes occurrences)
      (formula_arityTwoOrThree
        source sourcePlacement presentation.routes arity)
      (incidenceRoutes_variableRoutesInOccurrenceOrder
        presentation.toContinuousPlanarIncidencePresentation
        sourceDistinct variableOrdered)
      (incidenceRoutes_ternaryClauseRoutesInClockwiseOrder
        presentation.toContinuousPlanarIncidencePresentation clauseOrdered)

/-- The drawing stored by the padded polarity-normalized presentation keeps
distinct lifted route occurrences disjoint.  This is the stronger separation
certificate consumed by the later degree-three normalization compiler. -/
theorem paddedPeriodicThreeDMContinuousPlanarPresentation_separated
    {Variable : Type*} [DecidableEq Variable]
    {source : PositionedPeriodicCNF Variable}
    {sourcePlacement : PeriodicVariablePlacement Variable}
    (presentation :
      PositionedPeriodicCNF.HaloBoundedRibbonReadyIncidencePresentation
        source sourcePlacement)
    (sourceUnitSteps :
      (PositionedPeriodicCNF.incidenceDrawing
        source sourcePlacement presentation.routes).HasUnitSteps)
    (sourceDistinct : source.AllAtomsNodup)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase)
    (variableOrdered :
      source.VariableRoutesInOccurrenceOrder presentation.routes)
    (clauseOrdered :
      source.TernaryClauseRoutesInClockwiseOrder presentation.routes) :
    (paddedPeriodicThreeDMContinuousPlanarPresentation
      presentation sourceUnitSteps sourceDistinct occurrences arity
      variableOrdered clauseOrdered).drawing.LiftedRoutesAvoidEachOther := by
  let normalizedPresentation :=
    haloBoundedRibbonReadyPresentation presentation sourceUnitSteps
  simpa [paddedPeriodicThreeDMContinuousPlanarPresentation,
    normalizedPresentation,
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedContinuousPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedContinuousAssemblyGeometry,
    PeriodicPlanarOneInThreeToThreeDM.ContinuousAssemblyGeometry.toContinuousPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.assembledPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.assembledDrawing] using
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedLiftedRoutes_avoidEachOther
      normalizedPresentation
      (formula_widthAtMostThree
        source sourcePlacement presentation.routes arity)
      (formula_polarityNormalized
        source sourcePlacement presentation.routes)
      (formula_occurrencesAtMostThree_canonicalBEq
        source sourcePlacement presentation.routes occurrences)
      (formula_arityTwoOrThree
        source sourcePlacement presentation.routes arity)
      (incidenceRoutes_variableRoutesInOccurrenceOrder
        presentation.toContinuousPlanarIncidencePresentation
        sourceDistinct variableOrdered)
      (incidenceRoutes_ternaryClauseRoutesInClockwiseOrder
        presentation.toContinuousPlanarIncidencePresentation clauseOrdered)

/-- Every route stored by the padded polarity-normalized presentation is a
simple orthogonal polyline. -/
theorem paddedPeriodicThreeDMContinuousPlanarPresentation_routesSimple
    {Variable : Type*} [DecidableEq Variable]
    {source : PositionedPeriodicCNF Variable}
    {sourcePlacement : PeriodicVariablePlacement Variable}
    (presentation :
      PositionedPeriodicCNF.HaloBoundedRibbonReadyIncidencePresentation
        source sourcePlacement)
    (sourceUnitSteps :
      (PositionedPeriodicCNF.incidenceDrawing
        source sourcePlacement presentation.routes).HasUnitSteps)
    (sourceDistinct : source.AllAtomsNodup)
    (occurrences : source.erase.OccurrencesAtMost 3)
    (arity : PeriodicOneInThreeNoUnits.ArityTwoOrThree source.erase)
    (variableOrdered :
      source.VariableRoutesInOccurrenceOrder presentation.routes)
    (clauseOrdered :
      source.TernaryClauseRoutesInClockwiseOrder presentation.routes) :
    ∀ route ∈
        (paddedPeriodicThreeDMContinuousPlanarPresentation
          presentation sourceUnitSteps sourceDistinct occurrences arity
          variableOrdered clauseOrdered).drawing.edgeRoutes,
      LocalIncidenceDrawing.RouteIsSimple route := by
  let normalizedPresentation :=
    haloBoundedRibbonReadyPresentation presentation sourceUnitSteps
  simpa [paddedPeriodicThreeDMContinuousPlanarPresentation,
    normalizedPresentation,
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedContinuousPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedContinuousAssemblyGeometry,
    PeriodicPlanarOneInThreeToThreeDM.ContinuousAssemblyGeometry.toContinuousPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.assembledPlanarPresentation,
    PeriodicPlanarOneInThreeToThreeDM.assembledDrawing] using
    PeriodicPlanarOneInThreeToThreeDM.paddedNormalizedCoordinatedAssembledEdgeRoutes_simple
      normalizedPresentation
      (formula_widthAtMostThree
        source sourcePlacement presentation.routes arity)
      (formula_occurrencesAtMostThree_canonicalBEq
        source sourcePlacement presentation.routes occurrences)
      (formula_arityTwoOrThree
        source sourcePlacement presentation.routes arity)
      (incidenceRoutes_variableRoutesInOccurrenceOrder
        presentation.toContinuousPlanarIncidencePresentation
        sourceDistinct variableOrdered)
      (incidenceRoutes_ternaryClauseRoutesInClockwiseOrder
        presentation.toContinuousPlanarIncidencePresentation clauseOrdered)

end PeriodicOneInThreePolarityNormalizationRouteSubdivision
end LeanTrominoes
