/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFStripDirectSourceFormulaForwardLocal
import LeanTrominoes.PeriodicCNFStripDirectThreeCNFSourceZeroAnchors
import LeanTrominoes.PeriodicThreeSATThreeOccurrencePositiveOffsets

/-! # Copied-incidence offsets of the direct width-three source -/

noncomputable section

namespace LeanTrominoes
namespace PeriodicCNFStripReduction

variable {Input : Type}
variable {encoding : _root_.Computability.FinEncoding Input}
variable {language : Input → Prop}
variable (decider : Complexity.DeciderInPolySpace encoding language)

noncomputable local instance directOccurrenceOffsetStackFintype
    (stack : decider.tm.K) : Fintype (decider.tm.Γ stack) :=
  decider.stackAlphabetFinite stack

/-- Every copied occurrence incidence generated by the direct compiler
stays in the current slice or points to the next slice. -/
theorem directThreeCNFSource_occurrenceIncidences_positiveOffsets
    (symbols : List encoding.Γ) :
    ∀ incidence ∈ PeriodicThreeSATThree.occurrenceIncidences
        (PeriodicThreeCNF.formula
          (PeriodicCNF.PolySpaceCompiler.formulaOfSymbols
            decider symbols)),
      incidence.edge.offset = (0, 0) ∨
        incidence.edge.offset = (1, 0) := by
  apply PeriodicThreeSATThree.occurrenceIncidences_edge_offset_zero_or_one
  · exact PeriodicThreeCNF.formula_isForwardLocal
      (formulaOfSymbols_isForwardLocal decider symbols)
  · exact directThreeCNFSource_zeroAnchored decider symbols

end PeriodicCNFStripReduction
end LeanTrominoes
