/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.FiniteBlockIndexCompiler
import LeanTrominoes.PeriodicCNFStripDirectSourceFinalClauseDescriptorSemantics
import LeanTrominoes.PeriodicCNFStripDirectSourceFinalDistinctAtomIdentitySemantics
import LeanTrominoes.TM2EmptyAlphabetListInputCompiler
import LeanTrominoes.UnaryIndexedValueLookupCompiler
import LeanTrominoes.UnaryIndexedValueLookupSemantics

/-! # Retained source identities broadcast over final cycle occurrences -/

noncomputable section

namespace LeanTrominoes.PeriodicCNFStripReduction

open Computability Turing PeriodicCNF

variable {Input : Type}
variable {encoding : _root_.Computability.FinEncoding Input}
variable {language : Input → Prop}
variable (decider : Complexity.DeciderInPolySpace encoding language)

noncomputable local instance directFinalCycleInheritedIdentityStackFintype
    (stack : decider.tm.K) : Fintype (decider.tm.Γ stack) :=
  decider.stackAlphabetFinite stack

/-- Number of final Figure 9 occurrences generated by one finite-source
descriptor token's implication-cycle clause block. -/
def directSourceFinalCycleOccurrenceBlockLength
    (token : FormulaShapeDirectionOrdering.Token) : Nat :=
  (HorizontalRoutedRouteHeaderOccurrenceBlock.output
    (directSourceFinalCycleClauseDescriptorBlock token)).length

/-- Zero-based retained-variable indices, broadcast over every occurrence in
that variable's complete implication-cycle block. -/
def directSourceFinalCycleMarkerIndexQueries
    (symbols : List encoding.Γ) : List Nat :=
  FiniteBlockIndices.indices directSourceFinalCycleOccurrenceBlockLength
    (directRetainedFigureNineFiniteSourceVariableMarkers decider symbols)

@[simp] theorem directSourceFinalCycleMarkerIndexQueries_length
    (symbols : List encoding.Γ) :
    (directSourceFinalCycleMarkerIndexQueries decider symbols).length =
      (directSourceFinalCycleOccurrenceData decider symbols).length := by
  unfold directSourceFinalCycleMarkerIndexQueries
  rw [FiniteBlockIndices.indices_length]
  rw [directSourceFinalCycleOccurrenceData_eq_clauseDescriptors]
  unfold directSourceFinalCycleClauseDescriptors
    directSourceFinalCycleOccurrenceBlockLength
    HorizontalRoutedRouteHeaderOccurrenceBlock.output
  rw [List.flatMap_assoc, List.length_flatMap]

/-- Every broadcast marker query is in range of the distinct retained-source
identity column. -/
theorem directSourceFinalCycleMarkerIndexQuery_lt
    (symbols : List encoding.Γ) (query : Nat)
    (member : query ∈ directSourceFinalCycleMarkerIndexQueries
      decider symbols) :
    query <
      (directSourceFinalDistinctAtomIdentityIndices decider symbols).length := by
  unfold directSourceFinalCycleMarkerIndexQueries at member
  have bound := FiniteBlockIndices.mem_indices_lt_length
    directSourceFinalCycleOccurrenceBlockLength
    (directRetainedFigureNineFiniteSourceVariableMarkers decider symbols)
    query member
  rw [directSourceFinalDistinctAtomIdentityIndices_length_eq_markers]
  exact bound

/-- Look up the retained source identity belonging to every final cycle
occurrence. -/
def directSourceFinalCycleInheritedAtomIdentityIndices
    (symbols : List encoding.Γ) : List Nat :=
  UnaryIndexedValueLookup.values
    (directSourceFinalCycleMarkerIndexQueries decider symbols)
    (directSourceFinalDistinctAtomIdentityIndices decider symbols)

@[simp] theorem
    directSourceFinalCycleInheritedAtomIdentityIndices_length
    (symbols : List encoding.Γ) :
    (directSourceFinalCycleInheritedAtomIdentityIndices
      decider symbols).length =
      (directSourceFinalCycleOccurrenceData decider symbols).length := by
  unfold directSourceFinalCycleInheritedAtomIdentityIndices
  rw [UnaryIndexedValueLookup.values_length,
    directSourceFinalCycleMarkerIndexQueries_length]

noncomputable def
    directSourceFinalCycleMarkerIndexQueriesComputableInPolyTime :
    TM2ComputableInPolyTime id UnaryFieldEncoderMachine.unaryFields
      (directSourceFinalCycleMarkerIndexQueries decider) := by
  unfold directSourceFinalCycleMarkerIndexQueries
  exact TM2CompositionMachine.computableInPolyTime
    (directRetainedFigureNineFiniteSourceVariableMarkersComputableInPolyTime
      decider)
    (FiniteBlockIndices.indicesComputableInPolyTime
      directSourceFinalCycleOccurrenceBlockLength)

/-- Broadcast inherited source identities are polynomial-time computable,
including for the formally possible empty source alphabet. -/
noncomputable def
    directSourceFinalCycleInheritedAtomIdentityIndicesComputableInPolyTime :
    TM2ComputableInPolyTime id UnaryFieldEncoderMachine.unaryFields
      (directSourceFinalCycleInheritedAtomIdentityIndices decider) := by
  classical
  exact if nonemptyAlphabet : Nonempty encoding.Γ then by
    letI : Inhabited encoding.Γ :=
      ⟨Classical.choice nonemptyAlphabet⟩
    unfold directSourceFinalCycleInheritedAtomIdentityIndices
    exact UnaryIndexedValueLookup.valuesComputableInPolyTime
      id
      (directSourceFinalCycleMarkerIndexQueries decider)
      (directSourceFinalDistinctAtomIdentityIndices decider)
      (directSourceFinalCycleMarkerIndexQueriesComputableInPolyTime decider)
      (directSourceFinalDistinctAtomIdentityIndicesComputableInPolyTime
        decider)
  else by
    letI : IsEmpty encoding.Γ :=
      ⟨fun symbol => nonemptyAlphabet ⟨symbol⟩⟩
    exact TM2EmptyAlphabetListInputCompiler.computableInPolyTime
      UnaryFieldEncoderMachine.unaryFields _

end LeanTrominoes.PeriodicCNFStripReduction

end
