/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicOneInThreeToThreeDMOccurrences

/-!
# Well-formedness of the typed periodic 3DM construction

Every reference generated by a variable or clause-auxiliary triple names an
element in the corresponding finite typed element list.  This fact is
independent of the occurrence and clause-width bounds; those hypotheses enter
later when classifying degrees and matchings.
-/

namespace LeanTrominoes
namespace PeriodicOneInThreeToThreeDM

/-- A tagged occurrence's clause index lies in the source clause list. -/
theorem clauseIndex_lt_of_tagged_mem {Variable : Type*}
    (source : PeriodicCNF Variable)
    (tagged : TaggedOccurrence Variable)
    (member :
      tagged ∈ PeriodicThreeSATThree.taggedLiterals source) :
    tagged.2.1 < source.clauses.length := by
  simp only [PeriodicThreeSATThree.taggedLiterals,
    List.mem_flatMap, List.mem_map] at member
  rcases member with
    ⟨taggedClause, clauseMember, taggedLiteral, literalMember, taggedEq⟩
  subst tagged
  have lookup := (List.mem_zipIdx_iff_getElem?).mp clauseMember
  exact (List.getElem?_eq_some_iff.mp lookup).1

/-- Every atom appearing in a tagged occurrence is listed as occurring. -/
theorem atom_mem_occurringVariables_of_tagged_mem
    {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable)
    (tagged : TaggedOccurrence Variable)
    (member :
      tagged ∈ PeriodicThreeSATThree.taggedLiterals source) :
    tagged.1.atom ∈ occurringVariables source := by
  simp only [occurringVariables, List.mem_dedup]
  rw [← taggedLiterals_atoms source]
  exact List.mem_map.mpr ⟨tagged, member, rfl⟩

/-- Every internal red element of a listed variable gadget is declared. -/
theorem variableRed_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (atom : Variable)
    (atomMember : atom ∈ occurringVariables source)
    (element : PlanarThreeDM.VariableRed) :
    RedElement.variable atom element ∈ redElements source := by
  apply List.mem_append_left
  apply List.mem_flatMap.mpr
  refine ⟨atom, atomMember, List.mem_map.mpr ⟨element, ?_, rfl⟩⟩
  cases element <;> simp [allVariableReds]

/-- Every internal green element of a listed variable gadget is declared. -/
theorem variableGreen_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (atom : Variable)
    (atomMember : atom ∈ occurringVariables source)
    (element : PlanarThreeDM.VariableGreen) :
    GreenElement.variable atom element ∈ greenElements source := by
  apply List.mem_append_left
  apply List.mem_flatMap.mpr
  refine ⟨atom, atomMember, List.mem_map.mpr ⟨element, ?_, rfl⟩⟩
  cases element <;> simp [allVariableGreens]

/-- A valid source clause index names a declared red clause core. -/
theorem clauseRed_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (clauseIndex : Nat)
    (indexLt : clauseIndex < source.clauses.length) :
    RedElement.clause clauseIndex ∈ redElements source := by
  apply List.mem_append_right
  exact List.mem_map.mpr
    ⟨clauseIndex, List.mem_range.mpr indexLt, rfl⟩

/-- A valid source clause index names a declared green clause core. -/
theorem clauseGreen_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (clauseIndex : Nat)
    (indexLt : clauseIndex < source.clauses.length) :
    GreenElement.clause clauseIndex ∈ greenElements source := by
  apply List.mem_append_right
  exact List.mem_map.mpr
    ⟨clauseIndex, List.mem_range.mpr indexLt, rfl⟩

/-- A valid source clause index names a declared main blue element. -/
theorem clauseBlue_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (clauseIndex : Nat)
    (indexLt : clauseIndex < source.clauses.length) :
    BlueElement.clause clauseIndex ∈ blueElements source := by
  simp only [blueElements, List.mem_append]
  exact Or.inl <| Or.inl <| List.mem_map.mpr
    ⟨clauseIndex, List.mem_range.mpr indexLt, rfl⟩

/-- Every tagged occurrence names its declared complementary blue element. -/
theorem complementBlue_mem_of_tagged_mem
    {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable)
    (tagged : TaggedOccurrence Variable)
    (member :
      tagged ∈ PeriodicThreeSATThree.taggedLiterals source) :
    BlueElement.complement tagged.2.1 tagged.2.2 ∈
      blueElements source := by
  simp only [blueElements, List.mem_append]
  exact Or.inl <| Or.inr <|
    List.mem_map.mpr ⟨tagged, member, rfl⟩

/-- A slot whose occurrence lookup is empty has its declared private blue
cap. -/
theorem unusedBlue_mem {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) (atom : Variable)
    (atomMember : atom ∈ occurringVariables source)
    (slot : OccurrenceSlot)
    (unused : occurrenceAt source atom slot = none) :
    BlueElement.unused atom slot ∈ blueElements source := by
  simp only [blueElements, List.mem_append]
  apply Or.inr
  apply List.mem_map.mpr
  refine ⟨(atom, slot), ?_, rfl⟩
  apply List.mem_flatMap.mpr
  refine ⟨atom, atomMember, ?_⟩
  cases slot <;> simp [OccurrenceSlot.all, unused]

/-- The blue reference of every triple in a listed variable gadget is
declared. -/
theorem variableBlueElement_mem {Variable : Type*}
    [DecidableEq Variable] (source : PeriodicCNF Variable)
    (atom : Variable) (atomMember : atom ∈ occurringVariables source)
    (triple : PlanarThreeDM.VariableTriple) :
    variableBlueElement source atom triple ∈ blueElements source := by
  simp only [variableBlueElement]
  cases lookup :
      occurrenceAt source atom (variableTripleSlot triple) with
  | none =>
      exact unusedBlue_mem source atom atomMember
        (variableTripleSlot triple) lookup
  | some tagged =>
      have taggedData :=
        occurrenceAt_mem_and_atom source atom
          (variableTripleSlot triple) tagged lookup
      by_cases agrees : variableTripleValue triple = tagged.1.value
      · simpa [agrees] using
          clauseBlue_mem source tagged.2.1
            (clauseIndex_lt_of_tagged_mem source tagged taggedData.1)
      · simpa [agrees] using
          complementBlue_mem_of_tagged_mem source tagged taggedData.1

/-- Every reference of a listed variable-cycle triple is declared. -/
theorem variableTripleReferences_mem {Variable : Type*}
    [DecidableEq Variable] (source : PeriodicCNF Variable)
    (atom : Variable) (atomMember : atom ∈ occurringVariables source)
    (triple : PlanarThreeDM.VariableTriple) :
    (variableTripleReferences source atom triple).red.atom ∈
        redElements source ∧
      (variableTripleReferences source atom triple).green.atom ∈
        greenElements source ∧
      (variableTripleReferences source atom triple).blue.atom ∈
        blueElements source := by
  exact
    ⟨variableRed_mem source atom atomMember triple.references.red,
      variableGreen_mem source atom atomMember triple.references.green,
      variableBlueElement_mem source atom atomMember triple⟩

/-- Every reference of a clause-auxiliary triple arising from a tagged
literal is declared. -/
theorem clauseAuxiliaryReferences_mem {Variable : Type*}
    [DecidableEq Variable] (source : PeriodicCNF Variable)
    (tagged : TaggedOccurrence Variable)
    (member :
      tagged ∈ PeriodicThreeSATThree.taggedLiterals source) :
    (clauseAuxiliaryReferences
        (Variable := Variable) tagged.2.1 tagged.2.2).red.atom ∈
        redElements source ∧
      (clauseAuxiliaryReferences
        (Variable := Variable) tagged.2.1 tagged.2.2).green.atom ∈
        greenElements source ∧
      (clauseAuxiliaryReferences
        (Variable := Variable) tagged.2.1 tagged.2.2).blue.atom ∈
        blueElements source := by
  have indexLt := clauseIndex_lt_of_tagged_mem source tagged member
  exact
    ⟨clauseRed_mem source tagged.2.1 indexLt,
      clauseGreen_mem source tagged.2.1 indexLt,
      complementBlue_mem_of_tagged_mem source tagged member⟩

/-- The complete typed periodic 3DM construction is well formed. -/
theorem problem_isWellFormed {Variable : Type*} [DecidableEq Variable]
    (source : PeriodicCNF Variable) :
    (problem source).IsWellFormed := by
  intro triple tripleMember
  simp only [problem, triples, List.mem_append] at tripleMember
  rcases tripleMember with variableMember | auxiliaryMember
  · simp only [variableTriples, List.mem_flatMap,
      List.mem_map] at variableMember
    rcases variableMember with
      ⟨atom, atomMember, sourceTriple, sourceTripleMember, rfl⟩
    exact variableTripleReferences_mem
      source atom atomMember sourceTriple
  · simp only [clauseAuxiliaryTriples, List.mem_map] at auxiliaryMember
    rcases auxiliaryMember with ⟨tagged, taggedMember, rfl⟩
    exact clauseAuxiliaryReferences_mem source tagged taggedMember

end PeriodicOneInThreeToThreeDM
end LeanTrominoes
