/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFFormulaShapeFigureNineSourceTailData
import LeanTrominoes.PeriodicCNFStripHorizontalRoutedRouteHeaderTailData

/-! # Aligning finite Figure 9 headers with dynamic source tails -/

namespace LeanTrominoes
namespace PeriodicCNF
namespace FormulaShapeFigureNinePolarityRouteTail

open FormulaShapeDirectionOrdering
open FormulaShapeFigureNineRoutePrefix
open FormulaShapeFigureNinePolarityRouteHeader
open PeriodicCNFStripReduction

abbrev Header := FormulaShapeFigureNinePolarityRouteHeader.Header

/-- Select the dynamic clockwise source tail named by an inherited prefix.
Local routes deliberately select the empty word. -/
def selectedTailDirections
    (orderedTails : List (List AxisDirection))
    (header : Header) : List AxisDirection :=
  match header.figurePrefix with
  | .local _ => []
  | .inherited sourceSlot _ =>
      orderedTails.getD (sourceSlotNat sourceSlot) []

/-- Pair every final header generated by one source clause with the selected
dynamic tail of its inherited source prefix. -/
def sourceClausePairs (profile : DirectedClauseProfile)
    (orderedTails : List (List AxisDirection)) :
    List (Header × List AxisDirection) :=
  (sourceClauseHeaders profile).map fun header =>
    (header, selectedTailDirections orderedTails header)

/-- Delimited routed-header records for one clockwise source clause. -/
def sourceClauseRecords (profile : DirectedClauseProfile)
    (orderedTails : List (List AxisDirection)) :
    List PeriodicCNFStripReduction.HorizontalRoutedRouteHeaderTail.Token :=
  PeriodicCNFStripReduction.HorizontalRoutedRouteHeaderTail.records
    (sourceClausePairs profile orderedTails)

/-- Completing one clause's records produces exactly the compact routed
requests obtained by inserting its selected dynamic source tails. -/
@[simp] theorem output_sourceClauseRecords
    (profile : DirectedClauseProfile)
    (orderedTails : List (List AxisDirection)) :
    PeriodicCNFStripReduction.HorizontalRoutedRouteHeaderTail.output
        (sourceClauseRecords profile orderedTails) =
      (sourceClauseHeaders profile).flatMap fun header =>
        PeriodicCNFStripReduction.HorizontalRoutedRouteDirectionRequest.tokens
          (PeriodicCNFStripReduction.HorizontalRoutedRouteHeader.block header
            (selectedTailDirections orderedTails header)) := by
  unfold sourceClauseRecords sourceClausePairs
  rw [PeriodicCNFStripReduction.HorizontalRoutedRouteHeaderTail.output_records,
    List.flatMap_map]

/-- Consume one clockwise tail table for every directed clause descriptor;
variable markers consume no table because they create no source clause. -/
def sourceRecords :
    List FormulaShapeDirectionOrdering.Token →
      List (List (List AxisDirection)) →
        List PeriodicCNFStripReduction.HorizontalRoutedRouteHeaderTail.Token
  | [], _ => []
  | .variable :: source, tailTables =>
      sourceRecords source tailTables
  | .clause profile :: source, tailTables =>
      sourceClauseRecords profile (tailTables.headD []) ++
        sourceRecords source tailTables.tail

end FormulaShapeFigureNinePolarityRouteTail
end PeriodicCNF
end LeanTrominoes
