import LeanTrominoes.PeriodicOrthocrossingRetainedCarrierComputability

/-!
# Computability of the retained carrier formula

The retained carrier links are already a primitive-recursive finite list.
This module gives embedded clauses their canonical product encoding, proves
the generic positioned equality-clause constructors primitive recursive, and
thereby makes the selected retained carrier formula executable.
-/

noncomputable section

namespace LeanTrominoes
namespace PlanarThreeSAT

namespace EmbeddedClause

def equivData {Variable : Type*} : EmbeddedClause Variable ≃
    Cell × List (Variable × Bool) where
  toFun clause := (clause.position, clause.literals)
  invFun data := ⟨data.1, data.2⟩
  left_inv clause := by cases clause; rfl
  right_inv data := by cases data; rfl

noncomputable instance {Variable : Type*} [Primcodable Variable] :
    Primcodable (EmbeddedClause Variable) :=
  Primcodable.ofEquiv
    (Cell × List (Variable × Bool)) equivData

theorem equivData_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec (equivData (Variable := Variable)) :=
  Primrec.of_equiv

theorem equivData_symm_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec (equivData (Variable := Variable)).symm :=
  Primrec.of_equiv_symm

theorem position_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec (EmbeddedClause.position :
      EmbeddedClause Variable → Cell) :=
  (Primrec.fst.comp equivData_primrec).of_eq fun _ => rfl

theorem literals_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec (EmbeddedClause.literals :
      EmbeddedClause Variable → List (Variable × Bool)) :=
  (Primrec.snd.comp equivData_primrec).of_eq fun _ => rfl

theorem mk_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec fun data : Cell × List (Variable × Bool) =>
      EmbeddedClause.mk data.1 data.2 :=
  equivData_symm_primrec.of_eq fun _ => rfl

end EmbeddedClause

namespace EqualityLink

/-- The two positioned implication clauses generated by one equality link
are primitive recursive. -/
theorem equalityInstance_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec fun link : EqualityLink Variable =>
      equalityInstance link.first link.second link.positions := by
  have first := EqualityLink.first_primrec (Variable := Variable)
  have second := EqualityLink.second_primrec (Variable := Variable)
  have positions := EqualityLink.positions_primrec (Variable := Variable)
  have literal (variableFn : EqualityLink Variable → Variable)
      (variablePrimrec : Primrec variableFn) (value : Bool) :
      Primrec fun link : EqualityLink Variable =>
        (variableFn link, value) :=
    Primrec.pair variablePrimrec (Primrec.const value)
  have forwardLiterals : Primrec fun link : EqualityLink Variable =>
      [(link.first, true), (link.second, false)] :=
    Primrec.list_cons.comp
      (literal EqualityLink.first first true)
      (Primrec.list_cons.comp
        (literal EqualityLink.second second false)
        (Primrec.const []))
  have backwardLiterals : Primrec fun link : EqualityLink Variable =>
      [(link.first, false), (link.second, true)] :=
    Primrec.list_cons.comp
      (literal EqualityLink.first first false)
      (Primrec.list_cons.comp
        (literal EqualityLink.second second true)
        (Primrec.const []))
  have forward : Primrec fun link : EqualityLink Variable =>
      EmbeddedClause.mk link.positions.forward
        [(link.first, true), (link.second, false)] :=
    EmbeddedClause.mk_primrec.comp
      (Primrec.pair
        (EqualityPositions.forward_primrec.comp positions)
        forwardLiterals)
  have backward : Primrec fun link : EqualityLink Variable =>
      EmbeddedClause.mk link.positions.backward
        [(link.first, false), (link.second, true)] :=
    EmbeddedClause.mk_primrec.comp
      (Primrec.pair
        (EqualityPositions.backward_primrec.comp positions)
        backwardLiterals)
  exact (Primrec.list_cons.comp forward
    (Primrec.list_cons.comp backward (Primrec.const []))).of_eq
      fun _ => rfl

end EqualityLink

/-- Concatenating the two clauses of every equality link is primitive
recursive. -/
theorem equalityFamily_primrec
    {Variable : Type*} [Primcodable Variable] :
    Primrec (@equalityFamily Variable) :=
  Primrec.list_flatMap Primrec.id
    (EqualityLink.equalityInstance_primrec.comp₂ Primrec₂.right)

end PlanarThreeSAT

namespace PeriodicOrthocrossing

open PlanarThreeSAT

theorem retainedDrawingCompleteCarrierFormula_primrec
    {Vertex : Type*} [Primcodable Vertex] [DecidableEq Vertex] :
    Primrec (retainedDrawingCompleteCarrierFormula :
      PeriodicGraph Vertex → List (EmbeddedClause CarrierNode)) :=
  equalityFamily_primrec.comp
    retainedDrawingCompleteCarrierLinks_primrec

theorem retainedDrawingCompleteCarrierFormula_computable
    {Vertex : Type*} [Primcodable Vertex] [DecidableEq Vertex] :
    Computable (retainedDrawingCompleteCarrierFormula :
      PeriodicGraph Vertex → List (EmbeddedClause CarrierNode)) :=
  retainedDrawingCompleteCarrierFormula_primrec.to_comp

end PeriodicOrthocrossing
end LeanTrominoes
