/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicGraphCoreData

/-! # Syntactic periodic-CNF incidence metadata -/

namespace LeanTrominoes

/-- One syntactic literal occurrence together with its source clause
metadata. -/
structure CNFIncidence (Variable : Type*) where
  clauseIndex : Nat
  clause : PeriodicClause Variable
  literalIndex : Nat
  literal : PeriodicLiteral Variable
  deriving DecidableEq, Repr

namespace CNFIncidence

/-- The incidence-graph protoedge generated by this literal occurrence. -/
def edge {Variable : Type*} (incidence : CNFIncidence Variable) :
    PeriodicEdge (CNFVertex Variable) :=
  PeriodicCNF.incidenceEdge incidence.clauseIndex
    (PeriodicCNF.clauseAnchor incidence.clause) incidence.literal

end CNFIncidence

namespace PeriodicCNF

/-- All syntactic literal incidences in clause-major, literal-minor order. -/
def incidencesWithMetadata {Variable : Type*}
    (formula : PeriodicCNF Variable) : List (CNFIncidence Variable) :=
  formula.clauses.zipIdx.flatMap fun taggedClause =>
    taggedClause.1.zipIdx.map fun taggedLiteral =>
      ⟨taggedClause.2, taggedClause.1,
        taggedLiteral.2, taggedLiteral.1⟩

end PeriodicCNF
end LeanTrominoes
