import LeanTrominoes.PeriodicCNFPlanarOneInThreeNoUnitsPositioned

/-!
# Indexing the positioned unit-elimination replacement

Unit elimination is another variable-size `flatMap` of local clause blocks.
This module retains each source exact-one clause, its source presentation
index, and the local generated-clause index in a metadata list parallel to
the positioned output formula.
-/

namespace LeanTrominoes
namespace PeriodicOneInThreeNoUnitsPositioned

/-- Source and local indexing information for one clause generated by unit
elimination. -/
structure ClauseMetadata
    (Variable : Type*) where
  sourceClause : PositionedPeriodicClause Variable
  sourceClauseIndex : Nat
  clause :
    PositionedPeriodicClause
      (OneInThreeNoUnitVariable Variable)
  localClauseIndex : Nat

/-- The source-clause block and local generated-clause index uniquely name
one entry in the flattened unit-elimination metadata. -/
def ClauseMetadata.key
    {Variable : Type*}
    (metadata : ClauseMetadata Variable) : Nat × Nat :=
  (metadata.sourceClauseIndex, metadata.localClauseIndex)

/-- Index every generated clause in one source clause's local replacement
block. -/
def clauseMetadataFor
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable) :
    List (ClauseMetadata Variable) :=
  (clauseGadget sourceClauseIndex sourceClause).zipIdx.map
    fun taggedClause =>
      ⟨sourceClause, sourceClauseIndex,
        taggedClause.1, taggedClause.2⟩

/-- Metadata parallel to the complete flattened positioned unit-elimination
formula. -/
def formulaClauseMetadata
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable) :
    List (ClauseMetadata Variable) :=
  source.clauses.zipIdx.flatMap fun taggedSource =>
    clauseMetadataFor taggedSource.2 taggedSource.1

@[simp]
theorem clauseMetadataFor_clauses
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable) :
    (clauseMetadataFor
      sourceClauseIndex sourceClause).map
        ClauseMetadata.clause =
      clauseGadget sourceClauseIndex sourceClause := by
  simp [clauseMetadataFor, List.map_map,
    Function.comp_def]

/-- A local metadata entry retains its source clause and genuine local
generated-clause index. -/
theorem clauseMetadataFor_valid
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable)
    {metadata : ClauseMetadata Variable}
    (metadataMember :
      metadata ∈
        clauseMetadataFor sourceClauseIndex sourceClause) :
    metadata.sourceClause = sourceClause ∧
      metadata.sourceClauseIndex = sourceClauseIndex ∧
      (metadata.clause, metadata.localClauseIndex) ∈
        (clauseGadget
          sourceClauseIndex sourceClause).zipIdx := by
  rw [clauseMetadataFor] at metadataMember
  rcases List.mem_map.mp metadataMember with
    ⟨taggedClause, taggedClauseMember,
      metadataEqual⟩
  subst metadata
  exact ⟨rfl, rfl, taggedClauseMember⟩

/-- Local generated-clause indices do not repeat inside one source block. -/
theorem clauseMetadataFor_keys_nodup
    {Variable : Type*}
    (sourceClauseIndex : Nat)
    (sourceClause : PositionedPeriodicClause Variable) :
    ((clauseMetadataFor
      sourceClauseIndex sourceClause).map
        ClauseMetadata.key).Nodup := by
  let clauses := clauseGadget sourceClauseIndex sourceClause
  have indicesNodup :
      (clauses.zipIdx.map Prod.snd).Nodup :=
    List.nodup_zipIdx_map_snd clauses
  have keyedNodup :=
    indicesNodup.map
      (fun first second equal =>
        congrArg Prod.snd equal :
        Function.Injective fun localClauseIndex : Nat =>
          (sourceClauseIndex, localClauseIndex))
  unfold clauseMetadataFor
  rw [List.map_map]
  change
    (clauses.zipIdx.map
      ((fun localClauseIndex =>
        (sourceClauseIndex, localClauseIndex)) ∘ Prod.snd)).Nodup
  rw [List.map_map] at keyedNodup
  exact keyedNodup

/-- Forgetting the indexing metadata recovers the existing positioned
unit-elimination formula. -/
@[simp]
theorem formulaClauseMetadata_clauses
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable) :
    (formulaClauseMetadata source).map
        ClauseMetadata.clause =
      (formula source).clauses := by
  simp [formulaClauseMetadata, formula,
    List.map_flatMap]

/-- Every global metadata entry retains a genuine source-clause membership
and a genuine local generated-clause membership. -/
theorem formulaClauseMetadata_valid
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {metadata : ClauseMetadata Variable}
    (metadataMember :
      metadata ∈ formulaClauseMetadata source) :
    (metadata.sourceClause,
        metadata.sourceClauseIndex) ∈
      source.clauses.zipIdx ∧
    (metadata.clause, metadata.localClauseIndex) ∈
      (clauseGadget metadata.sourceClauseIndex
        metadata.sourceClause).zipIdx := by
  rw [formulaClauseMetadata,
    List.mem_flatMap] at metadataMember
  rcases metadataMember with
    ⟨taggedSource, taggedSourceMember,
      metadataMember⟩
  have valid :=
    clauseMetadataFor_valid
      taggedSource.2 taggedSource.1 metadataMember
  constructor
  · simpa [valid.1, valid.2.1] using
      taggedSourceMember
  · simpa [valid.1, valid.2.1] using
      valid.2.2

/-- Source-block/local-clause keys are pairwise distinct across the complete
flattened metadata enumeration. -/
theorem formulaClauseMetadata_keys_nodup
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable) :
    ((formulaClauseMetadata source).map
        ClauseMetadata.key).Nodup := by
  have sourceIndicesPairwise :
      source.clauses.zipIdx.Pairwise
        (fun first second => first.2 ≠ second.2) := by
    rw [← List.pairwise_map]
    exact List.nodup_zipIdx_map_snd source.clauses
  rw [formulaClauseMetadata, List.map_flatMap,
    List.nodup_flatMap]
  constructor
  · intro taggedSource _
    exact clauseMetadataFor_keys_nodup
      taggedSource.2 taggedSource.1
  · exact sourceIndicesPairwise.imp fun
      {first second} sourceIndexNe => by
        change List.Disjoint _ _
        rw [List.disjoint_left]
        intro key firstKeyMember secondKeyMember
        rcases List.mem_map.mp firstKeyMember with
          ⟨firstMetadata, firstMetadataMember, firstKeyEqual⟩
        rcases List.mem_map.mp secondKeyMember with
          ⟨secondMetadata, secondMetadataMember, secondKeyEqual⟩
        have firstValid :=
          clauseMetadataFor_valid
            first.2 first.1 firstMetadataMember
        have secondValid :=
          clauseMetadataFor_valid
            second.2 second.1 secondMetadataMember
        have metadataSourceIndicesEqual :=
          congrArg Prod.fst
            (firstKeyEqual.trans secondKeyEqual.symm)
        apply sourceIndexNe
        simpa [ClauseMetadata.key, firstValid.2.1,
          secondValid.2.1] using metadataSourceIndicesEqual

/-- Looking up a genuine flattened output clause yields metadata carrying
that exact clause. -/
theorem formulaClauseMetadata_lookup
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {clause :
      PositionedPeriodicClause
        (OneInThreeNoUnitVariable Variable)}
    {clauseIndex : Nat}
    (clauseMember :
      (clause, clauseIndex) ∈
        (formula source).clauses.zipIdx) :
    ∃ metadata,
      (formulaClauseMetadata source)[clauseIndex]? =
        some metadata ∧
      metadata.clause = clause := by
  have clauseLookup :
      (formula source).clauses[clauseIndex]? =
        some clause :=
    (List.mem_zipIdx_iff_getElem?).mp clauseMember
  have projectedLookup :
      ((formulaClauseMetadata source).map
          ClauseMetadata.clause)[clauseIndex]? =
        some clause := by
    simpa using clauseLookup
  rw [List.getElem?_map] at projectedLookup
  simpa only [Option.map_eq_some_iff] using
    projectedLookup

/-- A genuine flattened lookup also returns both membership invariants
needed to select the corresponding certified local drawing. -/
theorem formulaClauseMetadata_lookup_valid
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {clause :
      PositionedPeriodicClause
        (OneInThreeNoUnitVariable Variable)}
    {clauseIndex : Nat}
    (clauseMember :
      (clause, clauseIndex) ∈
        (formula source).clauses.zipIdx) :
    ∃ metadata,
      (formulaClauseMetadata source)[clauseIndex]? =
        some metadata ∧
      metadata.clause = clause ∧
      (metadata.sourceClause,
          metadata.sourceClauseIndex) ∈
        source.clauses.zipIdx ∧
      (metadata.clause, metadata.localClauseIndex) ∈
        (clauseGadget metadata.sourceClauseIndex
          metadata.sourceClause).zipIdx := by
  rcases formulaClauseMetadata_lookup
      source clauseMember with
    ⟨metadata, metadataLookup, clauseEqual⟩
  have metadataIndexLt :
      clauseIndex <
        (formulaClauseMetadata source).length :=
    (List.getElem?_eq_some_iff.mp metadataLookup).1
  have metadataAt :
      (formulaClauseMetadata source)[clauseIndex] =
        metadata :=
    (List.getElem?_eq_some_iff.mp metadataLookup).2
  have metadataMember :
      metadata ∈ formulaClauseMetadata source := by
    rw [← metadataAt]
    exact List.getElem_mem metadataIndexLt
  exact
    ⟨metadata, metadataLookup, clauseEqual,
      formulaClauseMetadata_valid
        source metadataMember⟩

/-- Equal source-block/local-clause keys returned by two metadata lookups
force the corresponding global generated-clause indices to be equal. -/
theorem formulaClauseMetadata_lookup_key_injective
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {firstMetadata secondMetadata : ClauseMetadata Variable}
    {firstClauseIndex secondClauseIndex : Nat}
    (firstLookup :
      (formulaClauseMetadata source)[firstClauseIndex]? =
        some firstMetadata)
    (secondLookup :
      (formulaClauseMetadata source)[secondClauseIndex]? =
        some secondMetadata)
    (keysEqual : firstMetadata.key = secondMetadata.key) :
    firstClauseIndex = secondClauseIndex := by
  have firstKeyLookup :
      ((formulaClauseMetadata source).map
        ClauseMetadata.key)[firstClauseIndex]? =
          some firstMetadata.key := by
    rw [List.getElem?_map, firstLookup]
    rfl
  have secondKeyLookup :
      ((formulaClauseMetadata source).map
        ClauseMetadata.key)[secondClauseIndex]? =
          some secondMetadata.key := by
    rw [List.getElem?_map, secondLookup]
    rfl
  rcases List.getElem?_eq_some_iff.mp firstKeyLookup with
    ⟨firstIndexLt, firstKeyAt⟩
  rcases List.getElem?_eq_some_iff.mp secondKeyLookup with
    ⟨secondIndexLt, secondKeyAt⟩
  have keyValuesEqual :
      ((formulaClauseMetadata source).map
        ClauseMetadata.key)[firstClauseIndex]'firstIndexLt =
      ((formulaClauseMetadata source).map
        ClauseMetadata.key)[secondClauseIndex]'secondIndexLt := by
    rw [firstKeyAt, secondKeyAt, keysEqual]
  exact
    ((formulaClauseMetadata_keys_nodup source).getElem_inj_iff
      (hi := firstIndexLt) (hj := secondIndexLt)).mp keyValuesEqual

/-- For two lookups in one source block, distinct global clause/literal
coordinates remain distinct after replacing the global clause indices by
their local block indices. -/
theorem localIncidencesDistinct_of_global
    {Variable : Type*}
    (source : PositionedPeriodicCNF Variable)
    {firstMetadata secondMetadata : ClauseMetadata Variable}
    {firstClauseIndex secondClauseIndex : Nat}
    {firstLiteralIndex secondLiteralIndex : Nat}
    (firstLookup :
      (formulaClauseMetadata source)[firstClauseIndex]? =
        some firstMetadata)
    (secondLookup :
      (formulaClauseMetadata source)[secondClauseIndex]? =
        some secondMetadata)
    (sameSource :
      firstMetadata.sourceClauseIndex =
        secondMetadata.sourceClauseIndex)
    (globalIncidencesDistinct :
      firstClauseIndex ≠ secondClauseIndex ∨
        firstLiteralIndex ≠ secondLiteralIndex) :
    firstMetadata.localClauseIndex ≠
        secondMetadata.localClauseIndex ∨
      firstLiteralIndex ≠ secondLiteralIndex := by
  by_cases localClausesDistinct :
      firstMetadata.localClauseIndex ≠
        secondMetadata.localClauseIndex
  · exact Or.inl localClausesDistinct
  · right
    intro literalIndicesEqual
    rcases globalIncidencesDistinct with
      clauseIndicesDistinct | literalIndicesDistinct
    · apply clauseIndicesDistinct
      apply formulaClauseMetadata_lookup_key_injective
        source firstLookup secondLookup
      exact Prod.ext sameSource
        (not_ne_iff.mp localClausesDistinct)
    · exact literalIndicesDistinct literalIndicesEqual

end PeriodicOneInThreeNoUnitsPositioned
end LeanTrominoes
