/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicOrthocrossingRouteDescriptorPairRouteShapeSelectionSemantics

/-! # Local offsets select complete affine route shapes -/

namespace LeanTrominoes
namespace PeriodicOrthocrossing
namespace RouteDescriptorPairAffine

/-- The finite straight/bent selector always matches its endpoint. -/
theorem FanoutShape.select_matches
    (endpoint : Endpoint) (descriptor : RouteDescriptor) :
    (FanoutShape.select endpoint descriptor).Matches endpoint descriptor := by
  by_cases straightMatches :
      FanoutShape.straight.Matches endpoint descriptor
  · rw [FanoutShape.select, if_pos straightMatches]
    exact straightMatches
  · rw [FanoutShape.select, if_neg straightMatches]
    cases endpoint <;>
      simpa [FanoutShape.Matches] using straightMatches

/-- Every zero, unit-horizontal, or unit-vertical descriptor offset selects
one of the seven finite core shapes. -/
theorem CoreShape.exists_matches_of_local_offset
    (descriptor : RouteDescriptor)
    (localOffset :
      descriptor.offset = (0, 0) ∨
      descriptor.offset = (1, 0) ∨
      descriptor.offset = (-1, 0) ∨
      descriptor.offset = (0, 1) ∨
      descriptor.offset = (0, -1)) :
    ∃ shape : CoreShape, shape.Matches descriptor := by
  rcases localOffset with zero | positiveHorizontal |
      negativeHorizontal | positiveVertical | negativeVertical
  · exact ⟨.zero, by simpa [CoreShape.Matches] using zero⟩
  · by_cases order :
        descriptorPortX descriptor.targetVertexIndex
            descriptor.targetPortRank <
          descriptorPortX descriptor.sourceVertexIndex
            descriptor.sourcePortRank
    · exact ⟨.positiveHorizontalDirect,
        by simpa [CoreShape.Matches] using And.intro positiveHorizontal order⟩
    · exact ⟨.positiveHorizontalBent,
        by simpa [CoreShape.Matches] using And.intro positiveHorizontal order⟩
  · by_cases order :
        descriptorPortX descriptor.sourceVertexIndex
            descriptor.sourcePortRank <
          descriptorPortX descriptor.targetVertexIndex
            descriptor.targetPortRank
    · exact ⟨.negativeHorizontalDirect,
        by simpa [CoreShape.Matches] using And.intro negativeHorizontal order⟩
    · exact ⟨.negativeHorizontalBent,
        by simpa [CoreShape.Matches] using And.intro negativeHorizontal order⟩
  · exact ⟨.positiveVertical,
      by simpa [CoreShape.Matches] using positiveVertical⟩
  · exact ⟨.negativeVertical,
      by simpa [CoreShape.Matches] using negativeVertical⟩

/-- Every descriptor with one of the five local offsets matches one of the
twenty-eight complete affine route shapes. -/
theorem RouteDescriptor.hasLocalShape_of_local_offset
    (descriptor : RouteDescriptor)
    (localOffset :
      descriptor.offset = (0, 0) ∨
      descriptor.offset = (1, 0) ∨
      descriptor.offset = (-1, 0) ∨
      descriptor.offset = (0, 1) ∨
      descriptor.offset = (0, -1)) :
    RouteDescriptorPairAffine.RouteDescriptor.HasLocalShape descriptor := by
  rcases CoreShape.exists_matches_of_local_offset descriptor localOffset with
    ⟨core, coreMatches⟩
  refine ⟨⟨FanoutShape.select .source descriptor, core,
    FanoutShape.select .target descriptor⟩, ?_⟩
  exact ⟨FanoutShape.select_matches .source descriptor, coreMatches,
    FanoutShape.select_matches .target descriptor⟩

/-- The three offsets generated by a forward-local CNF incidence are local
route shapes. -/
theorem RouteDescriptor.hasLocalShape_of_horizontal_offset
    (descriptor : RouteDescriptor)
    (horizontalOffset :
      descriptor.offset = (0, 0) ∨
      descriptor.offset = (1, 0) ∨
      descriptor.offset = (-1, 0)) :
    RouteDescriptorPairAffine.RouteDescriptor.HasLocalShape descriptor := by
  apply RouteDescriptor.hasLocalShape_of_local_offset descriptor
  rcases horizontalOffset with zero | positive | negative
  · exact Or.inl zero
  · exact Or.inr (Or.inl positive)
  · exact Or.inr (Or.inr (Or.inl negative))

end RouteDescriptorPairAffine
end PeriodicOrthocrossing
end LeanTrominoes
