/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFTransitionExprFormula
import LeanTrominoes.PeriodicCNFTransitionProgram
import LeanTrominoes.PeriodicCNFUnaryProgramTokens

/-! # Finite clause-arity scan of unary transition programs -/

namespace LeanTrominoes
namespace PeriodicCNF
namespace UnaryProgramClauseArity

/-- Every clause generated by the width-three transition compiler has one of
these three arities. -/
inductive Arity
  | unary
  | binary
  | ternary
  deriving DecidableEq, Fintype, Inhabited

def Arity.value : Arity → Nat
  | .unary => 1
  | .binary => 2
  | .ternary => 3

/-- Clause arities emitted by one postorder instruction, in exact compiler
order. -/
def instructionArities : TransitionInstruction → List Arity
  | .constant _ => [.unary]
  | .wire _ => [.binary, .binary]
  | .negate => [.binary, .binary]
  | .conjoin => [.binary, .binary, .ternary]
  | .disjoin => [.binary, .binary, .ternary]

/-- Recognize instruction tags in the finite unary stream.  Clause markers
and unary numeric payloads contribute no arity entries. -/
def tokenBlock : UnaryProgramTokens.Token → List Arity
  | .constant value => instructionArities (.constant value)
  | .wireStart nextSlice =>
      instructionArities (.wire
        ⟨if nextSlice then .next else .current, 0⟩)
  | .negate => instructionArities .negate
  | .conjoin => instructionArities .conjoin
  | .disjoin => instructionArities .disjoin
  | _ => []

def programScan (tokens : List UnaryProgramTokens.Token) : List Arity :=
  tokens.flatMap tokenBlock

/-- The program clauses are followed by the compiler's forced-root unary
clause. -/
def requestScan (tokens : List UnaryProgramTokens.Token) : List Arity :=
  programScan tokens ++ [.unary]

@[simp] theorem programScan_append
    (first second : List UnaryProgramTokens.Token) :
    programScan (first ++ second) =
      programScan first ++ programScan second := by
  simp [programScan]

@[simp] theorem programScan_replicate_freshUnit (count : Nat) :
    programScan (List.replicate count .freshUnit) = [] := by
  simp [programScan, tokenBlock]

@[simp] theorem programScan_replicate_atomUnit (count : Nat) :
    programScan (List.replicate count .atomUnit) = [] := by
  simp [programScan, tokenBlock]

@[simp] theorem programScan_instructionTokens
    (instruction : TransitionInstruction) :
    programScan (UnaryProgramTokens.instructionTokens instruction) =
      instructionArities instruction := by
  cases instruction with
  | constant value =>
      cases value <;>
        simp [UnaryProgramTokens.instructionTokens,
          UnaryProgramTokens.clauseTokens, programScan, tokenBlock,
          instructionArities]
  | wire input =>
      rcases input with ⟨slice, atom⟩
      cases slice <;>
        simp [UnaryProgramTokens.instructionTokens,
          UnaryProgramTokens.clauseTokens, UnaryProgramTokens.atomTokens,
          programScan, tokenBlock, instructionArities,
          ProgramTokens.sliceBool]
  | negate =>
      simp [UnaryProgramTokens.instructionTokens,
        UnaryProgramTokens.clauseTokens, programScan, tokenBlock,
        instructionArities]
  | conjoin =>
      simp [UnaryProgramTokens.instructionTokens,
        UnaryProgramTokens.clauseTokens, programScan, tokenBlock,
        instructionArities]
  | disjoin =>
      simp [UnaryProgramTokens.instructionTokens,
        UnaryProgramTokens.clauseTokens, programScan, tokenBlock,
        instructionArities]

@[simp] theorem programScan_ofProgram
    (program : TransitionProgram.Program) :
    programScan (UnaryProgramTokens.ofProgram program) =
      program.flatMap instructionArities := by
  induction program with
  | nil => rfl
  | cons instruction program induction =>
      rw [show UnaryProgramTokens.ofProgram (instruction :: program) =
          UnaryProgramTokens.instructionTokens instruction ++
            UnaryProgramTokens.ofProgram program by rfl,
        programScan_append, programScan_instructionTokens, induction]
      rfl

@[simp] theorem requestScan_requestSource
    (fresh : Nat) (program : TransitionProgram.Program) :
    requestScan (UnaryProgramTokens.requestSource fresh program) =
      program.flatMap instructionArities ++ [.unary] := by
  unfold requestScan UnaryProgramTokens.requestSource
  rw [programScan_append]
  rw [show programScan
      (.clauseMarker :: UnaryProgramTokens.ofProgram program) =
        programScan (UnaryProgramTokens.ofProgram program) by rfl,
    programScan_ofProgram]
  simp [UnaryProgramTokens.freshTokens, programScan, tokenBlock]

end UnaryProgramClauseArity
end PeriodicCNF
end LeanTrominoes
