/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFPlanarVariableNormalizationDegree

namespace LeanTrominoes
namespace PeriodicOrthocrossing

open PlanarThreeSAT

set_option maxHeartbeats 800000

/-- Periodicized routed-clause literal generated by one tagged incidence at
one explicit clause translation. -/
def routedSourcePeriodicLiteral
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) (translate : Cell)
    (taggedIncidence : CNFIncidence Variable × Nat) :
    PeriodicLiteral (PeriodicPlanarSATVariable Variable) :=
  let occurrence : CNFRouteOccurrence Variable :=
    ⟨taggedIncidence.1, taggedIncidence.2, translate⟩
  ⟨.terminal (occurrence.sourceTerminal formula).indexed .start,
    translate, taggedIncidence.1.literal.value⟩

/-- Subtracting the explicit source translation produces the zero-offset
prototype literal. -/
theorem routedSourcePeriodicLiteral_anchorNormalize
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) (translate : Cell)
    (taggedIncidence : CNFIncidence Variable × Nat) :
    PeriodicLiteral.anchorNormalize translate
        (routedSourcePeriodicLiteral
          formula translate taggedIncidence) =
      routedSourcePeriodicLiteral
        formula (0, 0) taggedIncidence := by
  rcases taggedIncidence with ⟨incidence, edgeIndex⟩
  rcases translate with ⟨translateX, translateY⟩
  simp [PeriodicLiteral.anchorNormalize,
    routedSourcePeriodicLiteral,
    CNFRouteOccurrence.sourceTerminal,
    CNFRouteOccurrence.taggedSegments,
    CNFRouteOccurrence.edge,
    Cell.sub]

/-- Anchor normalization erases the common explicit translation from a
routed source clause. -/
theorem routedSourcePeriodicClause_anchorNormalize
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (taggedIncidences : List (CNFIncidence Variable × Nat))
    (translate : Cell) :
    PeriodicClause.anchorNormalize
      (taggedIncidences.map
        (routedSourcePeriodicLiteral formula translate)) =
        taggedIncidences.map
          (routedSourcePeriodicLiteral formula (0, 0)) := by
  cases taggedIncidences with
  | nil =>
      rfl
  | cons first rest =>
      unfold PeriodicClause.anchorNormalize
      change
        ((first :: rest).map
          (routedSourcePeriodicLiteral formula translate)).map
            (PeriodicLiteral.anchorNormalize translate) =
          (first :: rest).map
            (routedSourcePeriodicLiteral formula (0, 0))
      rw [List.map_map]
      apply List.map_congr_left
      intro taggedIncidence _taggedIncidenceMem
      exact routedSourcePeriodicLiteral_anchorNormalize
        formula translate taggedIncidence

/-- Periodicizing a routed source clause exposes the common-translation
literal family above. -/
theorem periodicize_routedClauseAt
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (site : ClauseRouteSite) :
    PeriodicEquality.periodicizeClause
        (normalizePlanarSATNode
          (PeriodicCNF.incidenceGraph formula))
        (routedClauseAt formula site) =
      (((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
        fun taggedIncidence =>
          taggedIncidence.1.clauseIndex = site.1).map
            (routedSourcePeriodicLiteral formula site.2)) := by
  simp [PeriodicEquality.periodicizeClause,
    PeriodicEquality.periodicizeLiteral,
    routedClauseAt, clauseRouteOccurrencesAt,
    routedSourcePeriodicLiteral,
    normalizePlanarSATNode, normalizePlanarSATVariable,
    CNFRouteOccurrence.sourceTerminal,
    List.map_map, Function.comp_def]

/-- The anchor-normalized routed clause depends only on its prototype clause
index, not on the explicit neighboring translation. -/
theorem anchorNormalized_routedClauseAt
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (site : ClauseRouteSite) :
    (PeriodicEquality.periodicizeClause
      (normalizePlanarSATNode
        (PeriodicCNF.incidenceGraph formula))
      (routedClauseAt formula site)).anchorNormalize =
      (((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
        fun taggedIncidence =>
          taggedIncidence.1.clauseIndex = site.1).map
            (routedSourcePeriodicLiteral formula (0, 0))) := by
  rw [periodicize_routedClauseAt]
  exact routedSourcePeriodicClause_anchorNormalize
    formula _ site.2

/-- Anchor-normalized routed source clauses before clause deduplication. -/
def normalizedRoutedClauseClauses
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    List (PeriodicClause (PeriodicPlanarSATVariable Variable)) :=
  ((drawingRoutedClauseFormula formula).map
    (PeriodicEquality.periodicizeClause
      (normalizePlanarSATNode
        (PeriodicCNF.incidenceGraph formula)))).map
        PeriodicClause.anchorNormalize

/-- Every normalized routed source clause is the zero-offset prototype for
one represented clause site. -/
theorem normalizedRoutedClause_mem_witness
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    {clause :
      PeriodicClause (PeriodicPlanarSATVariable Variable)}
    (clauseMem : clause ∈ normalizedRoutedClauseClauses formula) :
    ∃ site ∈ drawingClauseRouteSites formula,
      clause =
        (((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
          fun taggedIncidence =>
            taggedIncidence.1.clauseIndex = site.1).map
              (routedSourcePeriodicLiteral formula (0, 0))) := by
  rcases List.mem_map.mp clauseMem with
    ⟨periodicClause, periodicClauseMem, clauseEq⟩
  rcases List.mem_map.mp periodicClauseMem with
    ⟨routedClause, routedClauseMem, periodicClauseEq⟩
  rcases List.mem_map.mp routedClauseMem with
    ⟨site, siteMem, routedClauseEq⟩
  subst clause
  subst periodicClause
  subst routedClause
  exact ⟨site, siteMem,
    anchorNormalized_routedClauseAt formula site⟩

/-- The zero-offset prototype literals for one source clause are
duplicate-free; their terminal route indices are the original globally
unique incidence indices. -/
theorem routedSourcePrototypeClause_nodup
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (clauseIndex : Nat) :
    (((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
      fun taggedIncidence =>
        taggedIncidence.1.clauseIndex = clauseIndex).map
          (routedSourcePeriodicLiteral formula (0, 0))).Nodup := by
  have taggedNodup :
      ((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
        fun taggedIncidence =>
          taggedIncidence.1.clauseIndex = clauseIndex).Nodup :=
    (List.nodup_zipIdx_map_snd
      (PeriodicCNF.incidencesWithMetadata formula)).of_map
        Prod.snd |>.filter _
  apply taggedNodup.map_on
  intro first firstMem second secondMem literalEq
  have atomEq :=
    congrArg PeriodicLiteral.atom literalEq
  have indexedEq :
      ((⟨first.1, first.2, (0, 0)⟩ :
        CNFRouteOccurrence Variable).sourceTerminal formula).indexed =
      ((⟨second.1, second.2, (0, 0)⟩ :
        CNFRouteOccurrence Variable).sourceTerminal formula).indexed := by
    exact
      (PeriodicPlanarSATVariable.terminal.inj atomEq).1
  have indexEq : first.2 = second.2 :=
    congrArg IndexedGridSegment.routeIndex indexedEq
  have firstGlobalMem :
      first ∈
        (PeriodicCNF.incidencesWithMetadata formula).zipIdx :=
    (List.mem_filter.mp firstMem).1
  have secondGlobalMem :
      second ∈
        (PeriodicCNF.incidencesWithMetadata formula).zipIdx :=
    (List.mem_filter.mp secondMem).1
  exact tagged_eq_of_mem_zipIdx_of_snd_eq
    firstGlobalMem secondGlobalMem indexEq

/-- A terminal prototype occurring in a normalized source clause identifies
a tagged source incidence at that clause index and route index. -/
theorem normalizedRoutedClause_terminal_witness
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    {clause :
      PeriodicClause (PeriodicPlanarSATVariable Variable)}
    {site : ClauseRouteSite}
    (clauseEq :
      clause =
        (((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
          fun taggedIncidence =>
            taggedIncidence.1.clauseIndex = site.1).map
              (routedSourcePeriodicLiteral formula (0, 0))))
    (indexed : IndexedGridSegment)
    (terminalMem :
      .terminal indexed .start ∈
        clause.map PeriodicLiteral.atom) :
    ∃ taggedIncidence ∈
        (PeriodicCNF.incidencesWithMetadata formula).zipIdx,
      taggedIncidence.1.clauseIndex = site.1 ∧
      taggedIncidence.2 = indexed.routeIndex := by
  rw [clauseEq] at terminalMem
  rcases List.mem_map.mp terminalMem with
    ⟨literal, literalMem, atomEq⟩
  rcases List.mem_map.mp literalMem with
    ⟨taggedIncidence, taggedIncidenceMem, literalEq⟩
  have indexedEq :
      ((⟨taggedIncidence.1, taggedIncidence.2, (0, 0)⟩ :
        CNFRouteOccurrence Variable).sourceTerminal formula).indexed =
        indexed := by
    exact
      (PeriodicPlanarSATVariable.terminal.inj
        ((congrArg PeriodicLiteral.atom literalEq).trans
          atomEq)).1
  exact
    ⟨taggedIncidence,
      (List.mem_filter.mp taggedIncidenceMem).1,
      of_decide_eq_true
        (List.mem_filter.mp taggedIncidenceMem).2,
      congrArg IndexedGridSegment.routeIndex indexedEq⟩

/-- Two normalized routed source clauses containing the same terminal
prototype are identical. -/
theorem normalizedRoutedClause_eq_of_terminal_mem
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (indexed : IndexedGridSegment)
    {first second :
      PeriodicClause (PeriodicPlanarSATVariable Variable)}
    (firstMem : first ∈ normalizedRoutedClauseClauses formula)
    (secondMem : second ∈ normalizedRoutedClauseClauses formula)
    (firstTerminalMem :
      .terminal indexed .start ∈
        first.map PeriodicLiteral.atom)
    (secondTerminalMem :
      .terminal indexed .start ∈
        second.map PeriodicLiteral.atom) :
    first = second := by
  rcases normalizedRoutedClause_mem_witness
    formula firstMem with
      ⟨firstSite, _firstSiteMem, firstEq⟩
  rcases normalizedRoutedClause_mem_witness
    formula secondMem with
      ⟨secondSite, _secondSiteMem, secondEq⟩
  rcases normalizedRoutedClause_terminal_witness
    formula firstEq indexed firstTerminalMem with
      ⟨firstTagged, firstTaggedMem,
        firstClauseIndexEq, firstRouteIndexEq⟩
  rcases normalizedRoutedClause_terminal_witness
    formula secondEq indexed secondTerminalMem with
      ⟨secondTagged, secondTaggedMem,
        secondClauseIndexEq, secondRouteIndexEq⟩
  have taggedEq :
      firstTagged = secondTagged :=
    tagged_eq_of_mem_zipIdx_of_snd_eq
      firstTaggedMem secondTaggedMem
      (firstRouteIndexEq.trans secondRouteIndexEq.symm)
  have siteIndexEq : firstSite.1 = secondSite.1 := by
    exact firstClauseIndexEq.symm.trans
      ((congrArg
        (fun tagged : CNFIncidence Variable × Nat =>
          tagged.1.clauseIndex) taggedEq).trans
        secondClauseIndexEq)
  rw [firstEq, secondEq, siteIndexEq]

theorem normalizedRoutedClause_literalAtoms_nodup
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    {clause :
      PeriodicClause (PeriodicPlanarSATVariable Variable)}
    (clauseMem : clause ∈ normalizedRoutedClauseClauses formula) :
    (clause.map PeriodicLiteral.atom).Nodup := by
  rcases normalizedRoutedClause_mem_witness
    formula clauseMem with ⟨site, _siteMem, clauseEq⟩
  rw [clauseEq]
  rw [List.map_map]
  have taggedNodup :
      ((PeriodicCNF.incidencesWithMetadata formula).zipIdx.filter
        fun taggedIncidence =>
          taggedIncidence.1.clauseIndex = site.1).Nodup :=
    (List.nodup_zipIdx_map_snd
      (PeriodicCNF.incidencesWithMetadata formula)).of_map
        Prod.snd |>.filter _
  apply taggedNodup.map_on
  intro first firstMem second secondMem atomEq
  have indexedEq :
      ((⟨first.1, first.2, (0, 0)⟩ :
        CNFRouteOccurrence Variable).sourceTerminal formula).indexed =
      ((⟨second.1, second.2, (0, 0)⟩ :
        CNFRouteOccurrence Variable).sourceTerminal formula).indexed :=
    (PeriodicPlanarSATVariable.terminal.inj atomEq).1
  have indexEq : first.2 = second.2 :=
    congrArg IndexedGridSegment.routeIndex indexedEq
  exact tagged_eq_of_mem_zipIdx_of_snd_eq
    (List.mem_filter.mp firstMem).1
    (List.mem_filter.mp secondMem).1 indexEq

/-- If each clause has no repeated atoms and at most one distinct listed
clause contains a target, then the flattened occurrence count is at most
one. -/
theorem flattenedClauseAtoms_count_le_one
    {Variable : Type*} [DecidableEq Variable]
    (target : Variable) :
    ∀ (clauses : List (PeriodicClause Variable)),
      clauses.Nodup →
      (∀ clause ∈ clauses,
        (clause.map PeriodicLiteral.atom).Nodup) →
      (∀ first ∈ clauses, ∀ second ∈ clauses,
        target ∈ first.map PeriodicLiteral.atom →
        target ∈ second.map PeriodicLiteral.atom →
        first = second) →
      (clauses.flatMap fun clause =>
        clause.map PeriodicLiteral.atom).count target ≤ 1 := by
  intro clauses
  induction clauses with
  | nil =>
      simp
  | cons clause clauses induction =>
      intro clausesNodup eachNodup uniqueClause
      have nodupData := List.nodup_cons.mp clausesNodup
      rw [List.flatMap_cons, List.count_append]
      by_cases targetMem :
          target ∈ clause.map PeriodicLiteral.atom
      · have tailTargetFree :
            target ∉
              clauses.flatMap fun tailClause =>
                tailClause.map PeriodicLiteral.atom := by
          intro tailMem
          rcases List.mem_flatMap.mp tailMem with
            ⟨tailClause, tailClauseMem, targetTailMem⟩
          have clauseEq :=
            uniqueClause clause (by simp)
              tailClause (by simp [tailClauseMem])
              targetMem targetTailMem
          subst tailClause
          exact nodupData.1 tailClauseMem
        rw [List.count_eq_zero_of_not_mem tailTargetFree,
          Nat.add_zero]
        exact
          (List.nodup_iff_count_le_one.mp
            (eachNodup clause (by simp))) target
      · rw [List.count_eq_zero_of_not_mem targetMem,
          Nat.zero_add]
        apply induction nodupData.2
        · intro tailClause tailClauseMem
          exact eachNodup tailClause (by simp [tailClauseMem])
        · intro first firstMem second secondMem
            firstTargetMem secondTargetMem
          exact uniqueClause first (by simp [firstMem])
            second (by simp [secondMem])
            firstTargetMem secondTargetMem

/-- Routed source clauses after anchor normalization and clause
deduplication. -/
def deduplicatedNormalizedRoutedClauseFormula
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    PeriodicCNF (PeriodicPlanarSATVariable Variable) :=
  ⟨(normalizedRoutedClauseClauses formula).dedup⟩

/-- Every source terminal prototype occurs in at most one literal of the
deduplicated normalized routed-clause family. -/
theorem
    deduplicatedNormalizedRoutedClauseFormula_terminal_count_le_one
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (indexed : IndexedGridSegment) :
    (deduplicatedNormalizedRoutedClauseFormula
      formula).variableOccurrences.count
        (.terminal indexed .start) ≤ 1 := by
  unfold deduplicatedNormalizedRoutedClauseFormula
    PeriodicCNF.variableOccurrences
  apply flattenedClauseAtoms_count_le_one
  · exact List.nodup_dedup _
  · intro clause clauseMem
    exact normalizedRoutedClause_literalAtoms_nodup
      formula (List.mem_dedup.mp clauseMem)
  · intro first firstMem second secondMem
      firstTargetMem secondTargetMem
    exact normalizedRoutedClause_eq_of_terminal_mem
      formula indexed
      (List.mem_dedup.mp firstMem)
      (List.mem_dedup.mp secondMem)
      firstTargetMem secondTargetMem

/-- Normalized routed source clauses use only `start` terminals, never
`finish` terminals. -/
theorem
    deduplicatedNormalizedRoutedClauseFormula_finish_count_eq_zero
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (indexed : IndexedGridSegment) :
    (deduplicatedNormalizedRoutedClauseFormula
      formula).variableOccurrences.count
        (.terminal indexed .finish) = 0 := by
  apply List.count_eq_zero_of_not_mem
  intro targetMem
  rcases List.mem_flatMap.mp targetMem with
    ⟨clause, clauseMem, literalAtomMem⟩
  have clauseRaw :
      clause ∈ normalizedRoutedClauseClauses formula :=
    List.mem_dedup.mp clauseMem
  rcases normalizedRoutedClause_mem_witness
    formula clauseRaw with
      ⟨site, _siteMem, clauseEq⟩
  rw [clauseEq] at literalAtomMem
  rcases List.mem_map.mp literalAtomMem with
    ⟨literal, literalMem, atomEq⟩
  rcases List.mem_map.mp literalMem with
    ⟨taggedIncidence, _taggedIncidenceMem, literalEq⟩
  have impossible :
      (routedSourcePeriodicLiteral
        formula (0, 0) taggedIncidence).atom =
          .terminal indexed .finish :=
    (congrArg PeriodicLiteral.atom literalEq).trans atomEq
  simp [routedSourcePeriodicLiteral] at impossible

/-- The normalized route wire followed by the normalized routed source
clauses. -/
def normalizedRouteWireAndClauseFormula
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    PeriodicCNF (PeriodicPlanarSATVariable Variable) :=
  ⟨(embedPeriodicCarrierFormula
      (Variable := Variable)
      (normalizedRouteWireFormula
        (PeriodicCNF.incidenceGraph formula))).clauses ++
    (deduplicatedNormalizedRoutedClauseFormula formula).clauses⟩

/-- A listed routed source terminal has at most thirty-six route-wire
occurrences and one routed-clause literal. -/
theorem normalizedRouteWireAndClauseFormula_sourceTerminal_count_le_seven
    {Variable : Type*} [DecidableEq Variable]
    {formula : PeriodicCNF Variable}
    (wellFormed :
      (PeriodicCNF.incidenceGraph formula).IsWellFormed)
    (degree :
      (PeriodicCNF.incidenceGraph formula).DegreeAtMost 3)
    (isLocal :
      (PeriodicCNF.incidenceGraph formula).IsLocal)
    {occurrence : CNFRouteOccurrence Variable}
    (occurrenceMem :
      occurrence ∈ drawingCNFRouteOccurrences formula) :
    (normalizedRouteWireAndClauseFormula
      formula).variableOccurrences.count
        (.terminal
          (occurrence.sourceTerminal formula).indexed .start) ≤ 7 := by
  have routeLe :=
    normalizedRouteWireFormula_sourceTerminal_count_le_six
      wellFormed degree isLocal occurrenceMem
  have embeddedRouteLe :
      (embedPeriodicCarrierFormula
        (Variable := Variable)
        (normalizedRouteWireFormula
          (PeriodicCNF.incidenceGraph formula))).variableOccurrences.count
            (.terminal
              (occurrence.sourceTerminal formula).indexed .start) ≤ 6 := by
    rw [embedPeriodicCarrierFormula_terminal_count]
    exact routeLe
  have clauseLe :=
    deduplicatedNormalizedRoutedClauseFormula_terminal_count_le_one
      formula (occurrence.sourceTerminal formula).indexed
  unfold normalizedRouteWireAndClauseFormula
    PeriodicCNF.variableOccurrences
  rw [List.flatMap_append, List.count_append]
  unfold PeriodicCNF.variableOccurrences at embeddedRouteLe
  unfold PeriodicCNF.variableOccurrences at clauseLe
  omega

/-- Normalized variable arms use target `finish` terminals, never source
`start` terminals. -/
theorem
    deduplicatedNormalizedRoutedVariableFormula_start_count_eq_zero
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable)
    (indexed : IndexedGridSegment) :
    (deduplicatedNormalizedRoutedVariableFormula
      formula).variableOccurrences.count
        (.terminal indexed .start) = 0 := by
  unfold deduplicatedNormalizedRoutedVariableFormula
  rw [PeriodicEquality.deduplicatedNormalizedFormula_occurrence_count]
  have endpointZero :
      (PeriodicEquality.normalizedLinkEndpoints
        (deduplicatedNormalizedRoutedVariableLinks formula)).count
          (.terminal indexed .start) = 0 := by
    apply List.count_eq_zero_of_not_mem
    intro targetMem
    rcases List.mem_flatMap.mp targetMem with
      ⟨link, linkMem, endpointMem⟩
    have linkRaw :
        link ∈
          (drawingRoutedVariableLinks formula).map
            (PeriodicEquality.normalizeLink
              (normalizePlanarSATNode
                (PeriodicCNF.incidenceGraph formula))) :=
      List.mem_dedup.mp linkMem
    rcases List.mem_map.mp linkRaw with
      ⟨source, sourceMem, linkEq⟩
    rcases drawingRoutedVariableLink_witness
      formula sourceMem with
        ⟨site, occurrence, _occurrenceMem, siteEq,
          sourceFirst, sourceSecond⟩
    subst link
    have normalized :=
      normalizeRoutedVariableLink_eq_of_witness
        formula siteEq sourceFirst sourceSecond
    rw [normalized] at endpointMem
    simp at endpointMem
  change
    2 * (PeriodicEquality.normalizedLinkEndpoints
      (deduplicatedNormalizedRoutedVariableLinks formula)).count
        (.terminal indexed .start) = 0
  rw [endpointZero]

/-- All periodically normalized external routed-SAT components, with each
translation-redundant component deduplicated before concatenation. -/
def normalizedExternalPlanarSATFormula
    {Variable : Type*} [DecidableEq Variable]
    (formula : PeriodicCNF Variable) :
    PeriodicCNF (PeriodicPlanarSATVariable Variable) :=
  ⟨(embedPeriodicCarrierFormula
      (Variable := Variable)
      (normalizedRouteWireFormula
        (PeriodicCNF.incidenceGraph formula))).clauses ++
    (deduplicatedNormalizedRoutedClauseFormula formula).clauses ++
    (deduplicatedNormalizedRoutedVariableFormula formula).clauses⟩

/-- The complete normalized external family uses a routed source terminal at
most thirty-seven times. -/
theorem
    normalizedExternalPlanarSATFormula_sourceTerminal_count_le_seven
    {Variable : Type*} [DecidableEq Variable]
    {formula : PeriodicCNF Variable}
    (wellFormed :
      (PeriodicCNF.incidenceGraph formula).IsWellFormed)
    (degree :
      (PeriodicCNF.incidenceGraph formula).DegreeAtMost 3)
    (isLocal :
      (PeriodicCNF.incidenceGraph formula).IsLocal)
    {occurrence : CNFRouteOccurrence Variable}
    (occurrenceMem :
      occurrence ∈ drawingCNFRouteOccurrences formula) :
    (normalizedExternalPlanarSATFormula
      formula).variableOccurrences.count
        (.terminal
          (occurrence.sourceTerminal formula).indexed .start) ≤ 7 := by
  have routeClauseLe :=
    normalizedRouteWireAndClauseFormula_sourceTerminal_count_le_seven
      wellFormed degree isLocal occurrenceMem
  have variableZero :=
    deduplicatedNormalizedRoutedVariableFormula_start_count_eq_zero
      formula (occurrence.sourceTerminal formula).indexed
  unfold normalizedRouteWireAndClauseFormula
    PeriodicCNF.variableOccurrences at routeClauseLe
  rw [List.flatMap_append, List.count_append] at routeClauseLe
  unfold normalizedExternalPlanarSATFormula
    PeriodicCNF.variableOccurrences
  rw [List.flatMap_append, List.flatMap_append,
    List.count_append, List.count_append]
  unfold PeriodicCNF.variableOccurrences at variableZero
  omega

/-- The complete normalized external family uses a routed target terminal at
most thirty-eight times. -/
theorem
    normalizedExternalPlanarSATFormula_targetTerminal_count_le_eight
    {Variable : Type*} [DecidableEq Variable]
    {formula : PeriodicCNF Variable}
    (wellFormed :
      (PeriodicCNF.incidenceGraph formula).IsWellFormed)
    (degree :
      (PeriodicCNF.incidenceGraph formula).DegreeAtMost 3)
    (isLocal :
      (PeriodicCNF.incidenceGraph formula).IsLocal)
    {occurrence : CNFRouteOccurrence Variable}
    (occurrenceMem :
      occurrence ∈ drawingCNFRouteOccurrences formula) :
    (normalizedExternalPlanarSATFormula
      formula).variableOccurrences.count
        (.terminal
          (occurrence.targetTerminal formula).indexed .finish) ≤ 8 := by
  have routeVariableLe :=
    normalizedRouteWireAndVariableFormula_targetTerminal_count_le_eight
      wellFormed degree isLocal occurrenceMem
  have clauseZero :=
    deduplicatedNormalizedRoutedClauseFormula_finish_count_eq_zero
      formula (occurrence.targetTerminal formula).indexed
  unfold normalizedRouteWireAndVariableFormula
    PeriodicCNF.variableOccurrences at routeVariableLe
  rw [List.flatMap_append, List.count_append] at routeVariableLe
  unfold normalizedExternalPlanarSATFormula
    PeriodicCNF.variableOccurrences
  rw [List.flatMap_append, List.flatMap_append,
    List.count_append, List.count_append]
  unfold PeriodicCNF.variableOccurrences at clauseZero
  omega

end PeriodicOrthocrossing
end LeanTrominoes
