/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanTrominoes.PeriodicCNFTransitionZeroAnchorData

/-! # Zero anchors of compiled transition expressions -/

namespace LeanTrominoes
namespace PeriodicCNF

/-- Every Tseitin clause generated by structural transition-expression
compilation begins with its current-slice gate output. -/
theorem compileTransitionExpr_clauses_zeroAnchored
    (expression : TransitionExpr) (fresh : Nat) :
    ClausesZeroAnchored
      (compileTransitionExpr expression fresh).clauses := by
  induction expression generalizing fresh with
  | constant value =>
      simp [compileTransitionExpr]
  | wire input =>
      simp [compileTransitionExpr]
  | not input induction =>
      simp only [compileTransitionExpr]
      apply clausesZeroAnchored_append
      · exact induction fresh
      · simp
  | and first second firstInduction secondInduction =>
      simp only [compileTransitionExpr]
      apply clausesZeroAnchored_append
      · apply clausesZeroAnchored_append
        · exact firstInduction fresh
        · exact secondInduction
            (compileTransitionExpr first fresh).nextFresh
      · simp
  | or first second firstInduction secondInduction =>
      simp only [compileTransitionExpr]
      apply clausesZeroAnchored_append
      · apply clausesZeroAnchored_append
        · exact firstInduction fresh
        · exact secondInduction
            (compileTransitionExpr first fresh).nextFresh
      · simp

end PeriodicCNF
end LeanTrominoes
