"""Produce independently kernel-checked completion gadget certificates.

Input: paper ASCII figures, commit b5f9568. Blank outer rows are removed.
Uppercase components are tiled separately (adjacent tiles sometimes reuse a
letter). Search is untrusted: Lean checks every positive tiling and every
exclusion step, including exhaustive coverage of placements at its pivot.
"""
from pathlib import Path
from functools import lru_cache
from itertools import product
from completion_minor_data import ROOT, SYMMETRIES, placement, finset


def cells_text(cells):
    return '⟨(↑([' + ','.join(f'({x},{y})' for x,y in sorted(cells)) + '] : List Cell) : Multiset Cell),by decide +kernel⟩'


def solver(kind, universe):
    shape = [(0,0),(1,0),(2,0) if kind == 'I' else (0,1)]
    pieces = sorted({frozenset((x+a,y+b) for a,b in [act(*q) for q in shape])
                     for x,y in universe for _,act in SYMMETRIES}, key=lambda p: sorted(p))
    pieces = [p for p in pieces if p <= universe]
    by_cell = {c: [p for p in pieces if c in p] for c in universe}
    failed = {}

    @lru_cache(None)
    def solve(rest):
        if not rest:
            return ()
        pivot = min(rest, key=lambda c: (sum(p <= rest for p in by_cell[c]),c))
        for piece in by_cell[pivot]:
            if piece <= rest:
                solution = solve(rest-piece)
                if solution is not None:
                    return (piece,) + solution
        failed[rest] = pivot
        return None
    return solve, failed


def generate(kind, name, full_boundary=False):
    rows = (ROOT/'data/completion'/kind/(name+'.asc')).read_text().splitlines()
    while not rows[0].strip(): rows.pop(0)
    while not rows[-1].strip(): rows.pop()
    grid = {(x,y):c for y,row in enumerate(rows) for x,c in enumerate(row) if c != ' '}
    holes = frozenset(p for p,c in grid.items() if c == '?')
    remaining = {p:c for p,c in grid.items() if c.isupper()}
    prefill = []
    while remaining:
        start = min(remaining); label = remaining[start]; todo = [start]; component = set()
        while todo:
            p = todo.pop()
            if remaining.get(p) != label: continue
            del remaining[p]; component.add(p); x,y = p
            todo.extend([(x+1,y),(x-1,y),(x,y+1),(x,y-1)])
        solution = solver(kind, frozenset(component))[0](frozenset(component))
        assert solution is not None
        prefill.extend(placement(kind,p) for p in solution)
    width = max(x for x,y in grid)+1; bottom = max(y for x,y in grid)
    left,right,block = (5,14,18) if kind == 'I' else (2,8,12)
    pairs = [((left+x,y),(right+x,y),y == 0) for y in [0,bottom] for x in range(0,width,block)]
    solve, failed = solver(kind,holes)
    records=[]
    if full_boundary:
        pairs = [(c,c,True) for l,r,top in pairs for c in [l,r]]
    for bits in product([False,True],repeat=len(pairs)):
        outside = (frozenset(l for (l,r,top),bit in zip(pairs,bits) if bit) if full_boundary else
                   frozenset(r if bit == top else l for (l,r,top),bit in zip(pairs,bits)))
        solution = solve(holes-outside) if outside <= holes and (len(holes)-len(outside)) % 3 == 0 else None
        records.append((outside,solution))
    # Failed branches encountered while finding positive witnesses are retained
    # too. Sorting by decreasing area puts every child after its parents.
    nodes = sorted(failed, key=lambda r:(-len(r), sorted(r)))
    ident = kind + ''.join(w.title() for w in name.split('-')) + ('Boundary' if full_boundary else '')
    ns = 'LeanTrominoes.CompletionPattern.'+ident
    out = ['/- Generated by scripts/completion_pattern_data.py. -/',
           'import LeanTrominoes.CompletionPatternIndexed', '', 'noncomputable section', '', 'namespace '+ns, '', 'set_option compiler.extract_closed false', 'set_option Elab.async false', 'set_option maxRecDepth 65536', 'set_option maxHeartbeats 0', '',
           'def prefillList : List (Placement Unit) := [' + ','.join(prefill) + ']',
           'def fixedCells : List Cell := [' + ','.join(f'({x},{y})' for (x,y),c in sorted(grid.items()) if c.isupper()) + ']',
           'def prefillSet : Finset (Placement Unit) := ⟨(↑prefillList : Multiset (Placement Unit)),by decide +kernel⟩',
           'def pattern : Pattern :=',f'  ⟨.{kind},{cells_text(grid)},prefillSet⟩', '',
           f'def outside (i : Fin {len(records)}) : Finset Cell := match i.val with']
    out += [f'  | {i} => {cells_text(o)}' for i,(o,s) in enumerate(records)]
    out += ['', f'def accepted (i : Fin {len(records)}) : Bool := match i.val with']
    out += [f'  | {i} => {str(s is not None).lower()}' for i,(o,s) in enumerate(records)]
    out += ['',f'def solutionList (i : Fin {len(records)}) : List (Placement Unit) := match i.val with']
    out += [f'  | {i} => ' + ('[' + ','.join(placement(kind,p) for p in s) + ']' if s is not None else '[]') for i,(o,s) in enumerate(records)]
    out += ['', f'def solution (i : Fin {len(records)}) := (solutionList i).toFinset', '',
            f'def residualList (i : Fin {len(records)}) : List Cell := match i.val with']
    out += [f'  | {i} => [' + ','.join(f'({x},{y})' for x,y in sorted(holes-o)) + ']' for i,(o,s) in enumerate(records)]
    out += ['']
    node_index = {r:i for i,r in enumerate(nodes)}
    shape = [(0,0),(1,0),(2,0) if kind == 'I' else (0,1)]
    for i,r in enumerate(nodes):
        x,y = failed[r]
        pieces = {frozenset((x+a-u,y+b-v) for a,b in [act(*q) for q in shape])
                  for _,act in SYMMETRIES for u,v in [act(*q) for q in shape]}
        children = sorted({node_index[r-piece]-i-1 for piece in pieces if piece <= r})
        assert all(j >= 0 for j in children)
        out.append(f'def exclusion{i} : TrominoFiniteIndexedExclusion.Node := ⟨{cells_text(r)},({x},{y}),[' + ','.join(map(str,children)) + ']⟩')
    out += ['', 'def certificate : List TrominoFiniteIndexedExclusion.Node := [' + ','.join(f'exclusion{i}' for i in range(len(nodes))) + ']', '', 'theorem certificate_checked :',
            '    TrominoFiniteIndexedExclusion.check pattern.tromino certificate = true := by decide +kernel', '',
            'theorem prefill_checked :',
            '    IsFiniteTiling (fun _ => pattern.tromino.cells) pattern.fixedRegion pattern.prefill := by',
            '  decide +kernel', '',
            f'theorem solutions_checked (i : Fin {len(records)}) : accepted i = true →',
            '    IsFiniteTiling (fun _ => pattern.tromino.cells) (pattern.residual (outside i)) (solution i) ∧',
            '      (∀ q ∈ pattern.prefill, q.cells (fun _ => pattern.tromino.cells) ⊆ pattern.target (outside i)) := by',
            '  revert i', '  decide +kernel', '',
            f'theorem rejections_checked (i : Fin {len(records)}) : accepted i = false →',
            '    pattern.rejectsIndexed (outside i) certificate = true := by',
            '  unfold Pattern.rejectsIndexed', '  rw [certificate_checked]', '  revert i', '  decide +kernel', '',
            f'theorem completable_iff (i : Fin {len(records)}) :',
            '    pattern.Completable (outside i) ↔ accepted i = true := by',
            '  cases h : accepted i',
            '  · exact iff_of_false (pattern.not_completable_of_rejectsIndexed _ certificate (rejections_checked i h)) (by decide)',
            '  · exact iff_of_true (pattern.completable_of_residual_solution _ _ prefill_checked (solutions_checked i h).2 (solutions_checked i h).1) rfl',
            '', 'end '+ns, '']
    out = [line.replace(f'  | {len(records)-1} =>', '  | _ =>') for line in out]
    split = out.index('theorem certificate_checked :')
    data = [line.replace('def ', 'noncomputable def ', 1) if line.startswith('def ') else line for line in out[:split]] + ['end '+ns, '']
    (ROOT/'LeanTrominoes'/('Completion'+ident+'Data.lean')).write_text(chr(10).join(data),encoding='utf-8',newline=chr(10))
    proof = ['/- Generated by scripts/completion_pattern_data.py. -/',
             'import LeanTrominoes.Completion'+ident+'Data', '', 'namespace '+ns, '',
             'set_option Elab.async false', 'set_option maxRecDepth 65536',
             'set_option maxHeartbeats 0', ''] + out[split:]
    (ROOT/'LeanTrominoes'/('Completion'+ident+'.lean')).write_text(chr(10).join(proof),encoding='utf-8',newline=chr(10))
    print(ident, len(nodes), 'exclusion nodes;',sum(s is not None for o,s in records),'accepted states',flush=True)


if __name__ == '__main__':
    for kind in ['I','L']:
        for name in ['plug-top','plug-bot','fill','dup','TFTSAT' if kind == 'I' else '3SAT']:
            generate(kind,name)
        for name in ['eq','neg','plug-top','plug-bot','fill']:
            generate(kind,name,full_boundary=True)
