"""Generate Lean coordinates from the paper's equal/not ASCII figures.

Sources: figs/{I,L}comp/{eq,neg}{,-T,-F}.asc from the trominoes paper
repository at commit b5f9568 (copied to data/completion).
Run from the repository root. Connected components of equal letters are tiles;
uppercase letters are prefill, lowercase letters are additions, and ? cells
are uncovered. Coordinates start at the upper left, with y increasing down.
The generated theorems are checked by Lean, independently of this parser.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMMETRIES = [
    ('identity', lambda x, y: (x, y)),
    ('rotate90', lambda x, y: (-y, x)),
    ('rotate180', lambda x, y: (-x, -y)),
    ('rotate270', lambda x, y: (y, -x)),
    ('reflectX', lambda x, y: (x, -y)),
    ('reflectDiagonal', lambda x, y: (y, x)),
    ('reflectY', lambda x, y: (-x, y)),
    ('reflectAntidiagonal', lambda x, y: (-y, -x)),
]


def read(kind, name):
    rows = (ROOT / 'data/completion' / kind / (name + '.asc')).read_text().splitlines()
    assert all(c == ' ' or c == '?' or c.isascii() and c.isalpha() for row in rows for c in row)
    return {(x, y): c for y, row in enumerate(rows) for x, c in enumerate(row) if c != ' '}


def components(grid):
    remaining = {p: c for p, c in grid.items() if c.isalpha()}
    result = []
    while remaining:
        first = min(remaining)
        label = remaining[first]
        todo, cells = [first], set()
        while todo:
            p = todo.pop()
            if remaining.get(p) != label:
                continue
            del remaining[p]
            cells.add(p)
            x, y = p
            todo.extend([(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)])
        assert len(cells) == 3, (label, cells)
        result.append((label, cells))
    return result


def placement(kind, cells):
    source = [(0, 0), (1, 0), (2, 0) if kind == 'I' else (0, 1)]
    for name, act in SYMMETRIES:
        rotated = [act(*p) for p in source]
        for x, y in sorted(cells):
            if {(x + a, y + b) for a, b in rotated} == cells:
                return f'⟨(),.{name},({x},{y})⟩'
    raise ValueError((kind, cells))


def finset(values):
    return '{' + ','.join(values) + '}' if values else '∅'


def main():
    out = ['/- Generated by scripts/completion_minor_data.py from data/completion. -/',
           'import LeanTrominoes.Tiling', '',
           'namespace LeanTrominoes.CompletionMinor', '',
           'inductive Gate | equal | negate deriving DecidableEq, Fintype', '']
    records = []
    for kind in ['I', 'L']:
        for gate, name in [('equal', 'eq'), ('negate', 'neg')]:
            base = read(kind, name)
            fixed = [placement(kind, cells) for label, cells in components(base) if label.isupper()]
            regions = finset(f'({x},{y})' for x, y in sorted(base))
            records.append((kind, gate, finset(fixed), regions))
    for field, typ, index in [('prefill', 'Finset (Placement Unit)', 2), ('region', 'Finset Cell', 3)]:
        out.append(f'def {field} : Tromino → Gate → {typ}')
        out.extend(f'  | .{k}, .{g} => {r[index]}' for r in records for k, g in [r[:2]])
        out.append('')
    out.append('def solution : Tromino → Gate → Bool → Finset (Placement Unit)')
    for kind in ['I', 'L']:
        for gate, name in [('equal', 'eq'), ('negate', 'neg')]:
            base = read(kind, name)
            for state, suffix in [('true', 'T'), ('false', 'F')]:
                grid = read(kind, name + '-' + suffix)
                assert grid.keys() == base.keys()
                assert all(grid[p] == c for p, c in base.items() if c.isupper())
                assert sum(c == '?' for c in grid.values()) == 2
                tiles = finset(placement(kind, cells) for _, cells in components(grid))
                out.append(f'  | .{kind}, .{gate}, {state} => {tiles}')
    out.extend(['', 'end LeanTrominoes.CompletionMinor', ''])
    (ROOT / 'LeanTrominoes/CompletionMinorData.lean').write_text('\n'.join(out), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
