"""Generate finite cap tilings; Lean independently checks every placement."""
from pathlib import Path
from completion_pattern_data import solver
from completion_minor_data import placement

ROOT = Path(__file__).resolve().parents[1]
HEADER = '''/-
Copyright (c) 2026 lean-trominoes contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LeanTrominoes.FiniteTrominoCompletion
import Mathlib.Data.Int.Interval

/-! # Fully prefilled collars for false strip-boundary connectors

Generated by `scripts/completion_strip_caps.py`. The top collar has two
full rows and a half-width third row. The bottom collar is its half-turn.
The solver is untrusted; both finite tilings are checked by the kernel.
-/
namespace LeanTrominoes.CompletionPattern.StripCaps

def width : Tromino → Int | .L => 12 | .I => 18

def topRegion (t : Tromino) : Finset Cell :=
  ((Finset.Ico 0 (width t)).product (Finset.Ico 0 3)).filter
    (fun c => c.2 < 2 ∨ c.1 < width t / 2)

def bottomRegion (t : Tromino) : Finset Cell :=
  ((Finset.Ico 0 (width t)).product (Finset.Ico 0 3)).filter
    (fun c => 0 < c.2 ∨ width t / 2 ≤ c.1)
'''

def generate():
    out = [HEADER]
    for side in ('top', 'bottom'):
        out.append(f'\ndef {side}Motif : Tromino → List (Placement Unit)')
        for kind, w in [('L', 12), ('I', 18)]:
            cells = frozenset(
                (x, y) for x in range(w) for y in range(3)
                if ((y < 2 or x < w//2) if side == 'top' else (y > 0 or x >= w//2)))
            solve, _ = solver(kind, cells)
            tiles = solve(cells)
            assert tiles is not None, (side, kind)
            out.append(f'  | .{kind} => [' + ','.join(placement(kind, tile) for tile in tiles) + ']')
        out.append(f'''
theorem {side}_tiling (t : Tromino) :
    IsFiniteTiling (fun _ => t.cells) ({side}Region t) ({side}Motif t).toFinset := by
  cases t <;> decide +kernel
''')
    out.append('\nend LeanTrominoes.CompletionPattern.StripCaps\n')
    (ROOT/'LeanTrominoes/CompletionStripCaps.lean').write_text('\n'.join(out), encoding='utf-8', newline='\n')

if __name__ == '__main__':
    generate()
