"""Certify self-contained I guards using only cells near their boundaries."""
from completion_i_guarded_data import guarded
from completion_pattern_data import ROOT, cells_text


def generate():
    lines = [
        '/- Generated by scripts/completion_i_barrier_data.py. -/',
        'import LeanTrominoes.CompletionIInteriorBarrier',
        'import LeanTrominoes.CompletionIRegionPartition',
        'import LeanTrominoes.CompletionConflictBarrierMonotone',
        'import LeanTrominoes.CompletionPatternMergeCover',
        '', 'noncomputable section',
        'namespace LeanTrominoes.CompletionPattern.IBricks',
        'set_option Elab.async false', 'set_option maxRecDepth 65536',
        'set_option maxHeartbeats 0', '',
    ]
    atoms = [('equal', 'eq'), ('negate', 'neg'), ('plugTop', 'plug-top'),
             ('plugBottom', 'plug-bot'), ('copy', 'dup'), ('clause', 'TFTSAT')]
    for atom, name in atoms:
        grid = guarded(name)
        height = max(y for x, y in grid)
        width = max(x for x, y in grid) + 1
        boundary = {(x, y) for x, y in grid if y in [0, height] and x % 18 in [5, 14]}
        core = sorted(p for p, char in grid.items() if not char.isupper() and p not in boundary)
        holes = sorted(p for p, char in grid.items() if char == '?')
        fringe = [c for c in core if not (2 <= c[0] and c[0] + 2 < width and 3 <= c[1] and c[1] + 2 < height)]
        ports = sorted({x for x, y in boundary})
        witnesses = {(x + dx, y) for x in ports for y in [2, height-2] for dx in [-1, 1]} | {(x, y) for x in ports for y in [4, height-4]}
        lines += [f'def {atom}Holes : List Cell := [' + ','.join(f'({x},{y})' for x, y in holes) + ']',
                  f'theorem {atom}_fixed_eq : Atom.fixed .{atom} = (Atom.pattern .{atom}).fixedRegion := by',
                  f'  have h := (Atom.pattern .{atom}).fixed_eq_of_merge (Atom.motif .{atom}) (Atom.prefill_list_eq .{atom}).symm (Atom.fixedList .{atom}) (by decide +kernel)',
                  f'  have eq : (Atom.fixedList .{atom}).toFinset = Atom.fixed .{atom} := CompletionCellOrder.toFinset_eq _ _',
                  '  exact eq.symm.trans h.symm',
                  f'theorem {atom}_holes_eq : (Atom.pattern .{atom}).region \\ Atom.fixed .{atom} = {atom}Holes.toFinset :=',
                  f'  Atom.holes_of_merge .{atom} {atom}Holes {atom}_fixed_eq (by decide +kernel)',
                  f'theorem {atom}_available_core : Atom.available .{atom} ⊆ Atom.core .{atom} := by',
                  f'  change ∀ c ∈ Atom.available .{atom}, c ∈ Atom.core .{atom}',
                  f'  simp only [Atom.core,{atom}_holes_eq,Finset.mem_sdiff,List.mem_toFinset]',
                  '  decide +kernel', '']
        lines += [f'def {atom}Fringe : Finset Cell := {cells_text(fringe, ordered=True)}',
                  f'def {atom}Witnesses : Finset Cell := {cells_text(witnesses, ordered=True)}',
                  f'theorem {atom}_witnesses_fixed : {atom}Witnesses ⊆ Atom.fixed .{atom} := by decide +kernel',
                  f'theorem {atom}_fringe_checked : CompletionBarrier.GuardedCheck .I {atom}Fringe',
                  f'    (Atom.pattern .{atom}).region {atom}Witnesses (Atom.available .{atom}) := by',
                  '  unfold CompletionBarrier.GuardedCheck',
                  '  simp only [Finset.subset_iff,Atom.mem_region]',
                  '  decide +kernel',
                  f'theorem {atom}_fringe_cover : ∀ c ∈ Atom.core .{atom}, (Atom.Interior .{atom} c) ∨ c ∈ {atom}Fringe := by',
                  f'  simp only [Atom.core,{atom}_holes_eq,Finset.mem_sdiff,List.mem_toFinset,and_imp]',
                  '  decide +kernel',
                  f'theorem {atom}_guarded : CompletionBarrier.GuardedCheck .I (Atom.core .{atom})',
                  f'    (Atom.pattern .{atom}).region (Atom.fixed .{atom}) (Atom.available .{atom}) := by',
                  f'  apply Atom.guarded_of_fringe .{atom} {atom}Fringe {atom}_fringe_cover',
                  f'  exact CompletionBarrier.guarded_mono_blocked _ _ _ _ _ _ {atom}_witnesses_fixed {atom}_fringe_checked']
        lines += ['']
    lines += ['theorem Atom.fixed_eq (a : Atom) : a.fixed = a.pattern.fixedRegion := by',
              '  cases a'] + [f'  · exact {atom}_fixed_eq' for atom, _ in atoms]
    lines += ['', 'theorem Atom.available_core (a : Atom) : a.available ⊆ a.core := by',
              '  cases a'] + [f'  · exact {atom}_available_core' for atom, _ in atoms]
    lines += ['', '/-- Centered crossing tiles strand an interior wire cell; all other crossings hit a prefill. -/',
              'theorem Atom.guarded (a : Atom) :',
              '    CompletionBarrier.GuardedCheck .I a.core a.pattern.region a.fixed a.available := by',
              '  cases a'] + [f'  · exact {atom}_guarded' for atom, _ in atoms]
    lines += ['', 'end LeanTrominoes.CompletionPattern.IBricks', '']
    (ROOT / 'LeanTrominoes/CompletionIAtomBarriers.lean').write_text('\n'.join(lines), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    generate()
