"""Certify the guarded I regions by linear comparisons of ordered cell lists."""
from completion_i_guarded_data import guarded
from completion_pattern_data import ROOT

atoms = [('equal', 'eq'), ('negate', 'neg'), ('plugTop', 'plug-top'),
         ('plugBottom', 'plug-bot'), ('copy', 'dup'), ('clause', 'TFTSAT')]
lines = ['/- Generated by scripts/completion_i_region_data.py. -/',
         'import LeanTrominoes.CompletionIAtomBarrierData',
         'import LeanTrominoes.CompletionGuardedShape',
         '', 'noncomputable section', 'namespace LeanTrominoes.CompletionPattern.IBricks',
         'set_option Elab.async false', 'set_option maxRecDepth 65536', 'set_option maxHeartbeats 0', '',
         'def Atom.width : Atom → Nat | .copy | .clause => 36 | _ => 18',
         'def Atom.height : Atom → Nat | .copy => 54 | _ => 27',
         'def Atom.regionCells : Atom → List Cell']
for atom, name in atoms:
    cells = ','.join(f'({x},{y})' for x, y in sorted(guarded(name)))
    lines += [f'  | .{atom} => [{cells}]']
lines += ['', 'theorem Atom.region_val (a : Atom) : a.pattern.region.val = (↑a.regionCells : Multiset Cell) := by',
          '  cases a <;> rfl',
          'theorem Atom.region_cells (a : Atom) : a.regionCells = CompletionGuardedShape.cells a.width a.height := by',
          '  cases a <;> decide +kernel',
          'theorem Atom.mem_region (a : Atom) (c : Cell) : c ∈ a.pattern.region ↔ CompletionGuardedShape.Member a.width a.height c := by',
          '  have eq : c ∈ a.pattern.region ↔ c ∈ a.regionCells := by',
          '    change c ∈ a.pattern.region.val ↔ _',
          '    rw [a.region_val]', '    rfl',
          '  rw [eq,a.region_cells,CompletionGuardedShape.mem_cells]',
          '', 'end LeanTrominoes.CompletionPattern.IBricks', '']
(ROOT / 'LeanTrominoes/CompletionIRegionGeometry.lean').write_text('\n'.join(lines), encoding='utf-8', newline='\n')
