/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedTftsatCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedTftsat
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix24 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail24 = true := by decide +kernel

theorem certificatePrefix25 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail25 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedTftsat
