/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedTftsatCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedTftsat
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix0 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificate = true := by decide +kernel

theorem certificatePrefix1 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail1 = true := by decide +kernel

theorem certificatePrefix2 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail2 = true := by decide +kernel

theorem certificatePrefix3 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail3 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedTftsat
