/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedTftsatCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedTftsat
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix4 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail4 = true := by decide +kernel

theorem certificatePrefix5 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail5 = true := by decide +kernel

theorem certificatePrefix6 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail6 = true := by decide +kernel

theorem certificatePrefix7 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail7 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedTftsat
