/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedTftsatCertificate.Tails

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedTftsat
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

theorem certificatePrefix8 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail8 = true := by decide +kernel

theorem certificatePrefix9 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail9 = true := by decide +kernel

theorem certificatePrefix10 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail10 = true := by decide +kernel

theorem certificatePrefix11 :
    TrominoFiniteListExclusion.checkPrefix pattern.tromino 16 certificateTail11 = true := by decide +kernel

end LeanTrominoes.CompletionPattern.IGuardedTftsat
