/- Generated by scripts/completion_pattern_data.py. -/
import LeanTrominoes.CompletionIGuardedTftsatData
import LeanTrominoes.TrominoFiniteListExclusionChunks

noncomputable section
namespace LeanTrominoes.CompletionPattern.IGuardedTftsat
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 0

def certificateTail1 := certificate.drop 16
def certificateTail2 := certificateTail1.drop 16
def certificateTail3 := certificateTail2.drop 16
def certificateTail4 := certificateTail3.drop 16
def certificateTail5 := certificateTail4.drop 16
def certificateTail6 := certificateTail5.drop 16
def certificateTail7 := certificateTail6.drop 16
def certificateTail8 := certificateTail7.drop 16
def certificateTail9 := certificateTail8.drop 16
def certificateTail10 := certificateTail9.drop 16
def certificateTail11 := certificateTail10.drop 16
def certificateTail12 := certificateTail11.drop 16
def certificateTail13 := certificateTail12.drop 16
def certificateTail14 := certificateTail13.drop 16
def certificateTail15 := certificateTail14.drop 16
def certificateTail16 := certificateTail15.drop 16
def certificateTail17 := certificateTail16.drop 16
def certificateTail18 := certificateTail17.drop 16
def certificateTail19 := certificateTail18.drop 16
def certificateTail20 := certificateTail19.drop 16
def certificateTail21 := certificateTail20.drop 16
def certificateTail22 := certificateTail21.drop 16
def certificateTail23 := certificateTail22.drop 16
def certificateTail24 := certificateTail23.drop 16
def certificateTail25 := certificateTail24.drop 16
def certificateTail26 := certificateTail25.drop 16
end LeanTrominoes.CompletionPattern.IGuardedTftsat
